### ISSUE TITLE
html double escape in options.html

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixos-search#105]
the javascript in https://github.com/NixOS/nixos-homepage/blob/master/nixos/options.tt#L233 appears to escape < and > twice

an example can be seen on https://nixos.org/nixos/options.html by searching for services.znc.confOptions.passBlock

**Comment by garbas** [comment]
https://search.nixos.org/options?show=services.znc.confOptions.passBlock&query=services.znc.confoptions.passblock&from=0&size=15&sort=relevance&channel=unstable#disabled

**Comment by ncfavier** [comment]
After discussing with @Infinisil, this is a mistake on nixpkgs' side, nothing to do with nixos-search.
