### ISSUE TITLE
Support for aliases

### ISSUE THREAD

**Issue by kristoff3r** [NixOS/nixos-search#115]
I just experienced that `nix search netcat` gave me the result `netcat-openbsd` while search.nixos.org didn't, which I guess is because `netcat-openbsd` is an alias for `libressl.nc`. I don't know if it's possible/feasible to support aliases here, but if it is then it would probably help a lot of people, since aliases are used to name things so they are easier to find for users.

**Comment by garbas** [comment]
@kristoff3r thank you for reporting. This I hope to get addressed with #39

**Comment by garbas** [comment]
This should be actually addressed when we add flakes support (#127), since there we will actually rewrite how we export the package set.

I'm closing this ticket, but creating a reference and a comment in flakes issue.
