### ISSUE TITLE
[call] suggestions remove duplicate documents

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#120]
If you search for `services.nginx.`, 

The first suggestion will be `services.` , which will be taken from any arbitrary *document*.

Since duplicates are removed, the document it's coming from will be removed from the results too, thus the full suggestion.

Let's assume `services.nginx` comes from `services.nginx.appendConfig`, the full `services.nginx.appendConfig` suggestion will not be in the suggestions.

**Comment by samueldr** [comment]
If possible, think that we also want suggestions for suffixes, if it can help.

```
services.
services.nginx.
services.nginx.appendConfig
nginx.appendConfig
appendConfig
nginx.
```

So if there are multiple solutions, and one of them helps with this...

**Comment by garbas** [comment]
suggestions were now reverted in #141
