### ISSUE TITLE
Relevance order needs tweaking when searching for rdp

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#131]
I searched for "rdp" and got results that don't even contain it, and the relevant result on the second page.

https://search.nixos.org/options?query=rdp&from=0&size=15&channel=unstable

![Screenshot from 2020-07-10 05-12-03](https://user-images.githubusercontent.com/91113/87112391-f1120280-c26b-11ea-90d6-ad9b1243d14b.png)

...

![Screenshot from 2020-07-10 05-12-50](https://user-images.githubusercontent.com/91113/87112438-130b8500-c26c-11ea-95ca-74f5209eceed.png)

So i guess we have to configure the search that the term with any prefix or suffix (like xrdp) has a higher priority than mutations of it (rtp).

**Comment by samueldr** [comment]
Spelling correction gone wrong with UDP?

I think so because of:

 * https://search.nixos.org/options?query=forefox

**Comment by garbas** [comment]
This is relevance tweaking bug, there are probably many more. thank you for reporting this one and please keep sending them.

@davidak Just for the future please write down also expected result order.
@samueldr Fuziness is configured to 1 (one character difference allowed), but clearly it should have less relevancy as it has now.

**Comment by davidak** [comment]
>Just for the future please write down also expected result order.

@garbas i have in the last sentence. also, it should be obvious here

1. xrdp (match with any prefix or suffix)
2. rtp (any fuzzy match)

**Comment by garbas** [comment]
This should be now fixed, please check and reopen if some result is missing.
