### ISSUE TITLE
Mitigate latency with access-control-max-age

### ISSUE THREAD

**Issue by JJJollyjim** [NixOS/nixos-search#153]
The `_search` endpoint currently lacks an access-control-max-age header, which doubles the latency of every request (OPTIONS + POST).

**Comment by garbas** [comment]
I'll raise this up with bonsai.io our elasticsearch provider. It looks that max-age header is stripped from the response.

**Comment by garbas** [comment]
The max-age is set to 3h (10800) and is already set. I was too fast to forward this to bonsai and didn't look good into the issue.
The max-age header is present in OPTIONS (preflight request) as it should be and is described at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by JJJollyjim** [comment]
Ah, that's very odd... firefox is still preflighting every request. I wonder if the fact that the POST has access-control-allow-origin without the -max-age overwrites the value that is stored by the options?
