### ISSUE TITLE
searching flakes and everything what flakes expose

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-search#164]
Currently most of packages/options are in nixpkgs. While discoverability is not great it was good enough for developers who just grepped the repo. One of the bigger reasons why everything is in one repo is that it is not easy for somebody - especially newcomer to nix - to combine multiple repositories with nix packages.

With flakes this will change since the basic unit that we will have is a flake. While nixpkgs is still going to be the repository with the biggest set of packages, we might also see other repositories showing up (eg. like NUR repository).

First step would be to do some UI wireframes and define what are the main user stories that we will optimize UI for.

**Comment by garbas** [comment]
closing this in favor of #125 (didn't know we already have this issue there)

**Comment by Mic92** [comment]
Right now the NUR flake exposes the `nur` attribute as an overlay. This does not make it easy to index packages in our repositories though. It is feasible to add all repositories to the `packages` output as well however there might be problems with the standard nix tooling that does not support nested attributes under `packages` i.e. `nur.packages.mic92.cntr`, when searching for it.
