### ISSUE TITLE
Search for "codium" does not show "vscodium"

### ISSUE THREAD

**Issue by Jiehong** [NixOS/nixos-search#170]
Hi,

First, searching for vscodium returns the correct package directly: https://search.nixos.org/packages?query=vscodium&from=0&size=15&sort=relevance&channel=20.03

![image](https://user-images.githubusercontent.com/1061229/91631616-3edcf880-e9db-11ea-8a26-b80b93242a08.png)

But searching for anything related to "codium", does not show this package at all: https://search.nixos.org/packages?query=codium&from=0&size=15&sort=relevance&channel=20.03

![image](https://user-images.githubusercontent.com/1061229/91631632-6207a800-e9db-11ea-9b4d-16166768bb43.png)

As a matter of fact, the term "codium" does not even appear in the list of results, yet "sodium" does, which is not even what I was looking for.

I also tried to search with terms such as "*codium", ".*codium", and "%codium" (with or without the quotes), and it didn't help.

Expected: searching for the term "codium" (non-quoted), should return "vscodium" at the very least.

Note: `nix search 'codium'` does return vscodium as expected.

**Comment by garbas** [comment]
We are currently using Elasticsearch 7.2 and to do wildcard search it would be to expensive (in performance) or we would have to increase the complexity (eg. introduce a cache layer).

In future version of Elasticsearch (7.9) there is an wildcard index that could potentially do this in a performant way, but we would have to test this. Also our Elasticsearch provider will have to provide us with this version.

To improve current situation I switch from `match` query to `match_bool_prefix` (#174) and also added the support for suffix (#176). It is not perfect, but works good enough and once we test how wilcard index performs we can consider switching to it.
