### ISSUE TITLE
Regression for searches with placeholders like `<name>`

### ISSUE THREAD

**Issue by Zopieux** [NixOS/nixos-search#187]
#149 was closed, but I believe the "fixed" behavior is broken too: instead of returning zero results, it returns way too many, rendering the search pretty useless.

It seems most people do prefix searches in search.nixos.org. So when searching for `nginx.<name>`, getting `services.grafana.database.name` as a [result](https://search.nixos.org/options?show=services.grafana.database.name&query=nginx.%3Cname%3E&from=30&size=30&sort=relevance&channel=unstable) makes very little sense.

I suggest treating `<[^\s>]+>` as special in the tokenizer, instead of making `<` and `>` behave like whitespace. IMHO, the `<foo>` convention (is it really a convention?) for placeholders is widespread enough to warrant special-casing it in the search engine.

**Comment by garbas** [comment]
This looks definitely like a regression. @Zopieux thank you for reporting it.
