### ISSUE TITLE
regex doesn't appear to work

### ISSUE THREAD

**Issue by petersjt014** [NixOS/nixos-search#188]
I was trying to search for all 'x2y' conversion tools with the regex `[a-z]{2,4}2[a-z]{2-4}` and found that this search doesn't behave as expected.

This seems to be true for simple ones too: when searching the string `2csv`, `xlsx2csv` is the only result. When searching `.*2csv`, there are a number of other results that shouldn't be there. At first I thought it was catching things in the metadata, but `csvkit` shows up and it doesn't even have a two in the title anywhere at all--so it's not that.

**Comment by petersjt014** [comment]
Also, `"2csv"` misbehaves too, and none of this is a problem with `nix search`.

**Comment by garbas** [comment]
@petersjt014 thank you for providing the feedback.

regex is not supported in search, we plan to add support for wildcard search but we would need to upgrade ElasticSearch instance to the latest which might take some time. For now only prefix and suffix search is supported.

Also currently `nix search` does not work as `search.nixos.org` but this will be addressed with #125.

But it is true initial search page should make better job at explaining how to search. I'll open a separate issue for that.
