### ISSUE TITLE
Impossible to Expand Search Results With Keyboard

### ISSUE THREAD

**Issue by raptortech-js** [NixOS/nixos-search#189]
For accessibility reasons, it's important that websites can be navigated and used fully without a mouse. There are many technologies that help people do this: frame navigation, caret navigation, screenreaders, and vimium's link hints mode. They all, however, require that the data they need be present on the page in some way. The results table of nixos-search presents as a plain table with option names and click handlers. Even if I use caret navigation to put my text cursor directly on the option name and hit enter, the click handler doesn't fire and I have no way to get at the information within. I'm not super familiar with the web, so I'm not sure what the right answer is here, but links would be awesome because those are super easy to find and activate.

**Comment by samueldr** [comment]
Implementation note:

Adding a proper `<a>` DOM element **with href** to the first column (attr name, option name) would help fix this. The concept being that the `<a>` prevents default on left click, and uses whatever "router" thing the app uses.

The href should point to whatever URL would be once the link is activated. This is (somewhat) useful as it allows middle-clicking on the attribute name to open a new tab with the option open.

The `<a>` could be set to `display: block;` to fill the whole `<td>`. Additionally `color: inherit` would help hide its linkyness.

We don't want to duplicate the `<a>` in every `<td>` of the row as it would make keyboard navigation quite harder.

**Comment by garbas** [comment]
I wonder if the result should actually be an unordered list (`ul`). 

@samueldr could we add this to the "redesign" bucket of issues and make sure we improve on it then?

**Comment by samueldr** [comment]
If adding a link is not too costly in time, it would be a good thing for accessibility reasons.

Though obviously, when re-doing the DOM+styles for the redesign that'll be tackled too,

**Comment by turboMaCk** [comment]
I think this can be even implemented in existing design in meantime. The approach can be then just ported during redesign work.

**Comment by garbas** [comment]
I think redesign work is just around the corner. We just need to separate `site-styles` folder from `nixos-homepage` and then we can start reusing it.

**Comment by jakeisnt** [comment]
#258 and #259 address this in part.
