### ISSUE TITLE
Searching for ansible in the 20.03 channel results in an error

### ISSUE THREAD

**Issue by HanEmile** [NixOS/nixos-search#193]
![2020-09-16-211937_951x369_scrot](https://user-images.githubusercontent.com/22756350/93382638-b1b2f400-f862-11ea-8e6b-07b4d27f3d38.png)

```
Problem with the value at json.hits.hits[0]['_source']['package_maintainers'][2].email: null Expecting a STRING
```

**Comment by notmgsk** [comment]
Likewise when searching "zsh".
