### ISSUE TITLE
Relevance score: use percentage of text that matches to attribute name?

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixos-search#196]
In case the search query matches or is close to an attribute name, it should return that as best matching result. 

This could be done by using as feature the percentage of the query text that matches to the text of the field.

I suppose the rating part is implemented in `search_fields`. Does it compute a score now per field?

**Comment by garbas** [comment]
@FRidh sorry it took some time for me to realized that I didn't replied to you.

> In case the search query matches or is close to an attribute name, it should return that as best matching result.
>
> This could be done by using as feature the percentage of the query text that matches to the text of the field.

I think the feature you are referring to is `fuzziness` and/or `minimum_should_match` that you can define in a [match query](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/query-dsl-match-query.html). I tried with both settings but reports I got were "Why I'm getting this results? I didn't typed that.". It confused more people that it actually helped, at least that I can tell from the reported issues so far. We can give it another type after some time, maybe even do A/B testing, but right now I would like to focus on other features (eg. flake support)

> I suppose the rating part is implemented in search_fields. Does it compute a score now per field?

Score is computed by match query, then per field you can provide boosting of that score.


I don't see anything actionable from this issue, but please reopen if you think I'm missing something and that I didn't address it.
