### ISSUE TITLE
URL query encoding of spaces is broken

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixos-search#200]
Spaces in the query part of an URL should be encoded as `+` ([source](https://stackoverflow.com/a/29948396)).
`nixos-search` uses `%20` instead.
This results in url https://search.nixos.org/options?query=a+b starting a query for `a+b` instead of `a b`, thereby breaking external tools like browser search plugins.

**Comment by samueldr** [comment]
Isn't this about *decoding*?

**Comment by erikarvstedt** [comment]
The biggest usability problem would be fixed if only **de**coding worked, yes.
But for consistency, spaces in the search box should also be encoded as `+` in the url.

**Comment by garbas** [comment]
@erikarvstedt can you provide an example of browser search plugin that uses search.nixos.org. Just so I can test it once I fix the code.

**Comment by erikarvstedt** [comment]
Chromium -> Settings -> Search engine -> Manage search engines -> Add:
- Name: nixos-options
- Keyword: no
- URL: https://search.nixos.org/options?query=%s

**Comment by turboMaCk** [comment]
elm's url package provides 2 functions for decoding & encoding urls (https://package.elm-lang.org/packages/elm/url/latest/Url#percentEncode) - this is what we should use.

**Comment by turboMaCk** [comment]
@erikarvstedt This is the version that uses standard url encoding (%20 for spaces) for query string within urls. Can you please test if it fixes the issue for you? https://5f9859cec9c1bb00f602c43b--nixos-search.netlify.app/

**Comment by erikarvstedt** [comment]
@turboMaCk, the main issue is fixed, thanks.
But `+` in the search field is correctly encoded to `%2B` in the URL, but it gets ignored [on decoding](https://5f98819934f3b70084ffe4bc--nixos-search.netlify.app/packages?channel=unstable&query=%2B):

**Comment by turboMaCk** [comment]
Yes I know about the issue bui I don't think there is a way to make this work without breaking +. details: https://github.com/NixOS/nixos-search/pull/215

**Comment by turboMaCk** [comment]
@erikarvstedt feel free to test the new behavior but I think it should resolve the issue to your satisfaction.
