### ISSUE TITLE
Use nixpkgs as name of the channel for example how to install it

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-search#201]
and mention nixos channel in case you are on NixOS

More from the twitter discussion https://twitter.com/zekjur/status/1311617711068377089

**Comment by stapelberg** [comment]
Specific replies that deserve attention (also because Twitter makes them hard to browse):

https://twitter.com/ioPhileas/status/1311581193062830080

> True, I'd be happy if it would say: "channel nixos not found, available channels: nixpkgs"

https://twitter.com/domenkozar/status/1311567418033045505

> We're running a campaign to improve such error messages https://opencollective.com/nix-errors-enhancement
> 
> In short, it's due to channels abstraction anti-pattern that is going away in Nix 3.

**Comment by turboMaCk** [comment]
resolved by https://github.com/NixOS/nixos-search/pull/261
