### ISSUE TITLE
Search should be case-insensitive

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixos-search#207]
I'm expecting to get a match for `systemPackages` when [searching for `systemp`](https://search.nixos.org/options?query=systemp).
The convenience of case-insensitive search far outweighs the negligible increase in ambiguity.
Ideally, the search should automatically enable case-sensitivity when the query contains capital chars.

**Comment by turboMaCk** [comment]
This also looks like ready for implementation. I guess this will require change in elastic search but I might be able to look into it if you're too busy with other stuff yourself @garbas.

**Comment by garbas** [comment]
@turboMaCk actually thank you for reminding me. It should be a quick fix, it just went away from my radar.
