### ISSUE TITLE
linuxPackages_latest not found even tho i can install it

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#209]
https://search.nixos.org/packages?query=v4l2loopback&from=0&size=30&sort=relevance&channel=20.09

![Screenshot from 2020-10-11 05-10-00](https://user-images.githubusercontent.com/91113/95669365-571a6880-0b80-11eb-9f65-a58f4443a52c.png)

not even https://search.nixos.org/packages?query=linuxPackages_latest.&from=0&size=30&sort=relevance&channel=20.09 is found on any channel

maybe because it's a alias for `linuxPackages_5_8`?

**Comment by garbas** [comment]
How we lookup for packages was copied from previous search implementation. Plan for next milestone is to rewrite it to also support flakes. Closing since this is going to be solved in #125
