### ISSUE TITLE
Literal examples are forcibly shown as an unreadable single line, instead of multi-line

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixos-search#210]
https://search.nixos.org/options?show=security.sudo.extraRules&query=security.sudo.extrarules

Please expand the first option.

Note that the literal example is basically impossible to read, as it is displayed as a single line with visible newline characters instead of being shown as a multi-line code block.

This feels like a somewhat big negative usability impact, sometimes a literal example is really helpful for figuring out how to specify nixos options for non-trivial modules.

**Comment by colemickens** [comment]
Here's an example:

![screenshot-1602977300](https://user-images.githubusercontent.com/327028/96355381-f4503200-1095-11eb-9a46-3a98ec8aae06.png)

**Comment by garbas** [comment]
@colemickens thank you for reporting.

This is a duplicate of https://github.com/NixOS/nixos-search/issues/161
