### ISSUE TITLE
Prompted for user/password when trying to search

### ISSUE THREAD

**Issue by bcc32** [NixOS/nixos-search#213]
When I try to search for any term, e.g.,:

https://search.nixos.org/packages?query=chicken&from=0&size=30&sort=relevance&channel=unstable

I am greeted by a sign in prompt, into which I have no idea what to enter.  Canceling the sign in prompt causes the search to fail with a 401 error.

Sign in prompt:
![Screenshot from 2020-10-19 16-53-00](https://user-images.githubusercontent.com/1239097/96510504-9a817080-122b-11eb-98ea-51de94fca027.png)

Error:
![Screenshot from 2020-10-19 16-53-14](https://user-images.githubusercontent.com/1239097/96510515-9e14f780-122b-11eb-834a-ed43caa397f7.png)

**Comment by garbas** [comment]
@bcc32 I'm not able to reproduce this. Does this still happen?

**Comment by bcc32** [comment]
Yes, this still happens, although I'm not able to reproduce on a different network or another device.  I think this is a corporate firewall issue rather than an issue on your end.  Apologies for the noise.

**Comment by garbas** [comment]
@bcc32 thank you for reporting anyway. In #52 we plan to setup the the reverse proxy and then this should be resolved also behind firewall.
