### ISSUE TITLE
Change default channel to latest-stable

### ISSUE THREAD

**Issue by plfaucher** [NixOS/nixos-search#220]
When opening either [packages](https://search.nixos.org/packages) or [options](https://search.nixos.org/options), the default channel is "unstable". I think that making the latest stable release (e.g.: 20.09 as of right now) the default channel would be a more reasonable default for most of the users.

**Comment by turboMaCk** [comment]
@garbas Is this something we want to do?

**Comment by plfaucher** [comment]
I've submitted the a PR in case this issue gets approved. I'm not particularily fluent in Elm, so maybe this isn't the "best" way of doing things. However, I've tested several solutions and this one is by far the simpler, and without any side effects since it does not change any existing type or function.

**Comment by garbas** [comment]
sounds good lets get this in. I'll comment separately on PR.
