### ISSUE TITLE
clicking the search button for a already loaded result shows inifite loading animation

### ISSUE THREAD

**Issue by BenediktSeidl** [NixOS/nixos-search#224]
### how to reproduce

* surf to https://search.nixos.org/packages?channel=20.09&from=0&size=30&sort=relevance&query=nixos
* click "Search" button
* see loading animation that never resolves to search result

### expected result

either
* fetching the search result again from api
* do nothing, but keep the previous search result

*tested the currently active version on https://search.nixos.org/ with chromium `80.0.3987.162` and firefox `68.8.0esr`*

**Comment by garbas** [comment]
@turboMaCk if you have time can you also look at this bug?

**Comment by turboMaCk** [comment]
@garbas sure!
