### ISSUE TITLE
'pytorchWithCuda' missing, when 'pytorchWithoutCuda' exists

### ISSUE THREAD

**Issue by cstich** [NixOS/nixos-search#226]
So confusingly `pytorchWithoutCuda` exists as a searchable package whereas `pytorchWithCuda` does not. The defintion of both of them is just 

```` 
pytorchWithCuda = self.pytorch.override { cudaSupport = true; };

pytorchWithoutCuda = self.pytorch.override { cudaSupport = false; };
````

so I am not sure why one is searchable and not the other.

**Comment by garbas** [comment]
@cstich thank you for reporting this. At the first glance I'm also not sure myself why this is the case. But maybe this means we are also not showing some other packages.

**Comment by jonringer** [comment]
pytorchWithCuda would be marked unfree. I'm assuming we are only exposing "free" packages

**Comment by cstich** [comment]
@jonringer That would make sense, but what about packages such as `steam` and `pytorch-bin`. Aren't those also unfree software?

**Comment by jonringer** [comment]
yes, but steam is "unfree redistributable". not sure about pytorch
