### ISSUE TITLE
Broken links to Nix expressions on GitHub

### ISSUE THREAD

**Issue by bnjmnt4n** [NixOS/nixos-search#228]
search.nixos.org provides broken links to the Nix expression source code on GitHub for packages, such as the following: https://github.com/NixOS/nixpkgs/blob/nixos-20.09/14cf906f33c.tar.gz/pkgs/applications/editors/emacs-modes/libgenerated.nix#L72. Seems like just the SHA-1 (without `.tar.gz`) or the channel should be included in the URL.

**Comment by garbas** [comment]
@bnjmnt4n thank you for taking the time to report the bug. can you also provide the link to the page you are seeing this error on?

**Comment by bnjmnt4n** [comment]
Seems like this occurs on any search for packages that is not on the unstable channel (eg. https://search.nixos.org/packages?channel=20.09&show=nix&from=0&size=30&sort=relevance&query=nix).

**Comment by garbas** [comment]
@bnjmnt4n it looks like something fishy is happening here. but it will be much faster to debug.

**Comment by turboMaCk** [comment]
@garbas feel free to just asign this to me if you want me to look into this
