### ISSUE TITLE
[Feature] Direct linking to package/option

### ISSUE THREAD

**Issue by BenediktSeidl** [NixOS/nixos-search#231]
*I'm not sure if this is a valid use case for nixos-search, feel free to close this ticket if it does not align with your mission*

I think it is a good feature of the search page that the state of the page is completely defined by the URL.

In my opinion the search page lacks the possibility to directly link to a package or a option. The current page can only link to a search page with the information of a certain package showing, but said package could be at the lower end of the list, so the first time user will not know that a certain package's information is showing because it's outside the viewport. I think there are two different ways to implement this feature (the workaround would be to define a search that only shows a single package/option):

### Scroll to and highlight selected package/option

When someone opens a link with a defined `show` query parameter, the package/option should be highlighted and the page should be scrolled, so the package/option is visible.
I think it is important, that the current behavior when clicking a package/option should not be changed, so the page should **not** scroll to show the package at a certain position when clicking on the package, this should only happen when opening from a link.

### Provide a separate page for direct links to package/option

A link symbol could be shown next to the package/option name. This links to a separate page that only shows the information of the package, but no other search results.
This could also be implemented by using #163 and providing a way to search for exact matches of package/option names

**Comment by garbas** [comment]
1. Scroll to and highlight selected package/option

I think this was actually working in the past. I'm actually not sure, but regardless it makes sense to add this feature.

2. Provide a separate page for direct links to package/option

This would definitely be a nice feature. There are many possibilities what to show on this page:
- which version of a package is in which channel
- see the history of a versions of a package for specific channel
- show open issues/PR regarding this package
and probably the list is endless.

I do want to work on other features before this, but I'm always going to find time to review a PR if it comes around and give a hand navigating the code base.

**Comment by turboMaCk** [comment]
bot things seems feasible to me. Feel free to assign it to me if you want once any of these is defined for implementation.

**Comment by garbas** [comment]
@turboMaCk if you have time please take care of 1.) ... we can open a discussion for 2.)
