### ISSUE TITLE
Show how to add a package on "No results" page

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-search#235]
Adding a help text with "How to add/request a package to nixpkgs?" with a link to the full documentation.

The link to the full documentation how to add a package is https://nixos.org/manual/nixpkgs/stable/#chap-quick-start

**Important**: we still need to show that there was no results as a main message.

**Comment by turboMaCk** [comment]
great idea!

**Comment by turboMaCk** [comment]
Once this has all the requirements, I can implement this if you want.

**Comment by garbas** [comment]
I added the link to the description of this issue. Is there something else needed?

**Comment by turboMaCk** [comment]
good. I think we can discuss rest under the PR.
