### ISSUE TITLE
nm-tui and nm-cli are missing

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixos-search#245]
The nix package manager has so far been great almost comparable to the AUR but a few packages I use like nm-tui and nm-cli are missing these make setting up WiFi really easy and should honesty be in the installer as well in my opinion I hate doing anything with setting up WiFi manually personally

**Comment by nonetrix** [comment]
Apparently nmtui exists in the repos but does not show up via search
![Screenshot_20201205-173915_Firefox-web](https://user-images.githubusercontent.com/45698918/101263119-8ecd0900-3708-11eb-874a-637726b38faa.png)

![Screenshot_20201205-144248](https://user-images.githubusercontent.com/45698918/101263128-98ef0780-3708-11eb-89fe-b0f76cf7792f.png)

**Comment by garbas** [comment]
Thank you for reporting.

I think the documentation does not mention that his are not the names of the packages, but names of the executables. At this point we don't index this, but we might do this in the future.

I'm closing this issue, since the feature is already planned.

**Comment by nonetrix** [comment]
thx :D
