### ISSUE TITLE
Option names containing angle brackets aren't rendered

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixos-search#247]
See for example https://search.nixos.org/options?channel=unstable&show=services.syncthing.declarative.devices.%3Cname%3E.id&from=0&size=30&sort=alpha_asc&query=syncthing

The `Name` field seems to be left empty if the option name contains angle brackets (I'm not sure why), causing every other field to be misaligned upwards.

**Comment by garbas** [comment]
I fixed this in #252
