### ISSUE TITLE
First query after reindexing takes ~30s

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-search#250]
We need to warm up internal elasticsearch cache once everything has been imported. This can also serve as a quick test that everything works.

**Comment by ncfavier** [comment]
Is the fix still working/needed? The queries seem to fail instantly: https://github.com/NixOS/nixos-search/runs/4825472635?check_suite_focus=true#step:9:1

**Comment by ncfavier** [comment]
Turns out they were using the wrong index names. Fixing in https://github.com/NixOS/nixos-search/pull/415
