### ISSUE TITLE
layout is wrong if some meta attribute is missing

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixos-search#265]
![image](https://user-images.githubusercontent.com/24027/104929932-76edd380-599c-11eb-98f7-1cfd7b8ef73d.png)

https://search.nixos.org/packages?channel=unstable&show=blackbox&from=0&size=30&sort=relevance&query=blackbox

**Comment by turboMaCk** [comment]
there is redesign on its way - resolved by #261

**Comment by bbigras** [comment]
Nice. Thanks!
