### ISSUE TITLE
Top navigation doesn't work on mobile

### ISSUE THREAD

**Issue by eahlberg** [NixOS/nixos-search#266]
The top navigation (hamburger menu) which shows up on smaller viewports doesn't show any content when clicked. Tried on mobile Safari, Firefox and Chrome.

**Comment by turboMaCk** [comment]
I've actually hit this as well yesterday! thanks for report.

**Comment by turboMaCk** [comment]
Resolved by https://github.com/NixOS/nixos-search/pull/267

Stayed tuned for more mobile experience improvements which are going to happen as part of faceted-search milestone and redesign / branding work though :)

**Comment by eahlberg** [comment]
Nice, looking forward to it!
