### ISSUE TITLE
Some nixos options are not index

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixos-search#269]
I've just found in which nixos-search doesn't show all available options.

See results for compton (picom):

![image](https://user-images.githubusercontent.com/2130305/105560253-988be980-5d13-11eb-99de-9f3c837f6030.png)

https://search.nixos.org/options?channel=unstable&show=services.compton&from=0&size=30&sort=relevance&query=compton

While the list options should be https://github.com/NixOS/nixpkgs/blob/da3378c4aaf2ed350ad14552558fa55bb68d96d3/nixos/modules/services/x11/picom.nix#L55-L262

**Comment by garbas** [comment]
The problem here is because `services.comptom` is an alias of `services.picom`. If you search for `picom` you will see the options.

**Comment by turboMaCk** [comment]
just for the records this issue contains some information regarding aliases - https://github.com/NixOS/nixos-search/issues/115

Thanks for clarification @garbas
