### ISSUE TITLE
Metadata messed up in nix-prefetch-git etc

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#270]
I noticed that for some packages the metadata is messed up.

![Screenshot from 2021-01-23 03-50-56](https://user-images.githubusercontent.com/91113/105566767-38567100-5d2e-11eb-964f-b176e0a86b62.png)

https://search.nixos.org/packages?channel=20.09&show=nix-prefetch-git&from=30&size=30&sort=relevance&query=nix

https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/tools/package-management/nix-prefetch-scripts/default.nix

- The License is missing, so the maintainer is displayed.
- Instead of the maintainer, the description is displayed
- The description is displayed as "Not specified" (which is wrong)
- For long version, there is nothing. here "Not specified" would be correct

**Comment by samueldr** [comment]
#261 re-does this interface. Meaning that, while this is valid, it won't be *fixed* as-is.

And yes, what is happening is that empty fields "disappear", following values go up once. This is why implementing a `<table>` like layout without using an actual `<table>` can sometimes be hard :).

**Comment by davidak** [comment]
>Meaning that, while this is valid, it won't be fixed as-is.

ah, yes. sure

i tested it there

![Screenshot from 2021-01-23 08-52-16](https://user-images.githubusercontent.com/91113/105572598-65b81480-5d58-11eb-8206-94d852f481ea.png)

Homepage is not displayed there which is OK

Version and License is just empty which looks broken

**Comment by turboMaCk** [comment]
I think problems like this or https://github.com/NixOS/nixos-search/issues/269 are not on the UI side but in the python script we're using to populate the ES.
