### ISSUE TITLE
Cannot select option names for easy copying

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixos-search#271]
Before the recent update, the name of the option was one of the things shown in the details of the option. This was useful for selecting and copying, e.g. to share option names via IRC or for pasting into configs. Now the redundant copy is missing, and the option "link" can't be selected.

**Comment by turboMaCk** [comment]
I believe you're referring to this meta attribute, is that correct?

![image](https://user-images.githubusercontent.com/2130305/105609219-10a3ef00-5da8-11eb-919c-bb3b82373ad5.png)

In meantime old version is still available: https://6008b7aa541b4b165ca9bd14--nixos-search.netlify.app/

**Comment by Artturin** [comment]
@turboMaCk `Nix expression` is missing and the `Name` which can be copied is missing from packages and options
![image](https://user-images.githubusercontent.com/56650223/105610186-0dfcc600-5db7-11eb-98e4-e0123230535f.png)

**Comment by turboMaCk** [comment]
I'll look into this as soon as I can. Thanks for opening the issue. I agree these things are useful and should be included. Any objection @garbas ?

**Comment by turboMaCk** [comment]
Thanks for clarification @Artturin & Iheckermann. I think this PR should resolve the situation https://github.com/NixOS/nixos-search/pull/275 even though there are more improvements that needs to be done, especially to the options search.
