### ISSUE TITLE
Sort selection is not working

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixos-search#276]
## Reproduce:

1. go to package or options search (https://search.nixos.org/packages?channel=20.09&from=0&size=50&sort=relevance&query=hello)
2. Click on Sort select

![image](https://user-images.githubusercontent.com/2130305/105708381-aceb0480-5f14-11eb-9328-e134a42f69db.png)

**Comment by garbas** [comment]
Stupid me what did I do! :smile:
