### ISSUE TITLE
Option search misses many results

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixos-search#279]
Specifically, more general searches (shorter input) seem to return fewer results (at least sometimes) than more specific searches (longer input that is a superstring of the shorter input from before).

For a concrete example, take a search for [`ftp`](https://search.nixos.org/options?channel=unstable&from=0&size=500&sort=alpha_asc&query=ftp):

  * 12 hits
  * One of those is for options in `services.atftpd`
  * Three are for `services.vsftpd`

But if we search for [`services.atftpd`](https://search.nixos.org/options?channel=unstable&from=0&size=500&sort=alpha_asc&query=services.atftpd) we get three options, rather than the one we got before, and a search for [`services.vsftpd`](https://search.nixos.org/options?channel=unstable&from=0&size=500&sort=alpha_asc&query=services.vsftpd) returns 28 -- more than the entire previous search for `ftp` did, even though the results should be a strict subset of that search!

This appears to have happened along with the recent redesign of the search page that adds a lot more vertical padding to the search results, but that might be a coincidence.

**Comment by garbas** [comment]
Thank you for reporting this. It definitely looks strange behavior.
