### ISSUE TITLE
UX improvement: Links in search results.

### ISSUE THREAD

**Issue by mintchaos** [NixOS/nixos-search#280]
in the results `GNU General Public License v2.0 or later`, `Homepage`, & `Source` are all links. But it's impossible to know this without hovering. In fact I thought the homepage/source links had been removed from the results with the new design and was pretty disappointed until a friend pointed out they were still there. I had assumed that entire line was purely informational.

![image](https://user-images.githubusercontent.com/1450/106174890-536c1b00-614a-11eb-8f7b-15b0457372f7.png)

Other links in the results are blue. But even underlines or something else would help here. The previous search results were definitely more scan-able. 

Also listing out the entire homepage url in the results like we used to helped provide context. Could know while scanning the list if it's the thing you were looking for or be able to infer things from if it was custom domain or a github url, etc.

**Comment by garbas** [comment]
I agree this is not done as good as it should be. I'm collecting this "visual" reports and I will resolve them as part of #286
