### ISSUE TITLE
steam-run Source link wrong

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#281]
When clicking on Source in steam-run package, https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/build-support/trivial-builders.nix#L7 opens. But that is not the actual code.

the correct link would be https://github.com/NixOS/nixpkgs/blob/f3d651ea9d4dab74cfca169e0294929015fc9ca6/pkgs/games/steam/fhsenv.nix#L269

## Steps to reproduce

https://search.nixos.org/packages?channel=20.09&show=steam-run&from=0&size=50&sort=relevance&query=steam-run

**Comment by garbas** [comment]
I would report this issue to nix repository since we are only reusing what `nix-env` provides.
