### ISSUE TITLE
Package search should not be case sensitive 

### ISSUE THREAD

**Issue by JonJFineman** [NixOS/nixos-search#285]
When searching for packages the search match is case sensitive. Since I don’t know how some packages are capitalized it would be better to not match based on search.

**Comment by garbas** [comment]
I thought that I messed up with the case sensitivity, but as far as I can tell it works:

https://search.nixos.org/packages?channel=20.09&show=haskellPackages.FpMLv53&from=0&size=50&sort=relevance&query=fpmlv

I'm closing the issue, but please send me the URL of the search that didn't work for you.

**Comment by JonJFineman** [comment]
This is the url that fails:
https://search.nixos.org/packages?query=Firefox

**Comment by garbas** [comment]
Ah right, I was testing the other way around :) probably we only need to lowercase the query string. Thank you!
