### ISSUE TITLE
Searching unstable does not reflect the current state of unstable, cannot find go_1_16

### ISSUE THREAD

**Issue by lobre** [NixOS/nixos-search#295]
Hi,

I cannot find `go_1_16` using this search query with the "unstable" channel.

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=go_1_16

It returns "No packages found" while `go_1_16` has been merged ~1 month ago (https://github.com/NixOS/nixpkgs/pull/107937).

If I check the current state of Hydra builds for unstable channels, they are green and the pointing commits correctly contain `go_1_16`.

https://github.com/NixOS/nixpkgs/blob/916ee862e87ac5ee2439f2fb7856386b4dc906ae/pkgs/top-level/all-packages.nix#L10331

So I was wondering if it was a bug, or if there was a delay before packages show up on nixos-search? I think people could get confused when searching "unstable" because they expect bleeding edge things there. I think 1 month delay is already a lot.

Thanks in advance for your help.

**Comment by sternenseemann** [comment]
The search for unstable seems to be *significantly* outdated in general. For example [bitwarden_rs is reported as 1.17](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=bitwarden_rs), but has been updated to 1.19 in February.

```
nix-instantiate -A bitwarden_rs '<nixpkgs>'
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/b3yq29rdbpfvawdgg23kgz77fj99iiw2-bitwarden_rs-1.19.0.drv
```
