### ISSUE TITLE
DocBook rendering is broken

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixos-search#303]
The rendering of DocBook option descriptions to HTML implemented in #86 using Pandoc has multiple problems. The ones I could find are all conveniently illustrated in the description for [environment.profileRelativeSessionVariables](https://search.nixos.org/options?channel=unstable&show=environment.profileRelativeSessionVariables&from=0&size=30&sort=relevance&query=environment.profileRelativeSessionVariables):

1. ~cross-reference (`xref` elements) titles are not resolved properly and are replaced with `???`. This is because the cross-referenced element isn't present in the snippet we feed to Pandoc.~
2. ~cross-reference links just point to `#${id}`, which has no effect on Elasticsearch. They should probably point to the appropriate anchor in [options.html](https://nixos.org/manual/nixos/stable/options.html), or to a search.nixos.org URL such as the one I crafted above, or we should somehow teach Elasticsearch to deal with those anchors.~
3. ~man page references (`citerefentry` elements) aren't rendered properly. Pandoc [doesn't seem to support](https://github.com/jgm/pandoc/blob/2d60524de43d59ffb1763a33a15cc2ecce613ecf/src/Text/Pandoc/Readers/DocBook.hs#L99) that element at all at the moment.~
4. descriptions aren't broken into paragraphs at `\n\n`, like they are in the manual. This is because this is part of the post-processing that happens in [`optionsDocBook`](https://github.com/NixOS/nixpkgs/blob/081b9423d4ae18836c7564b634627b214049f80e/nixos/lib/make-options-doc/default.nix#L191-L192) but not in `optionsJSON`.

I'm not sure how we should fix this. The ways I can think of are:

1. Parse the `options.html` generated by `manualHTML` directly. This avoids a lot of code duplication, descriptions are rendered exactly as they are in the manual. On the downside, it requires parsing HTML and making assumptions about the generated format (default values, examples etc. aren't properly separated from the description text; CSS classes used in the manual might clash with those used by Elasticsearch).
2. PR nixpkgs to expose the [`olinkDB`](https://github.com/NixOS/nixpkgs/blob/081b9423d4ae18836c7564b634627b214049f80e/nixos/doc/manual/default.nix#L131) which maps cross-reference IDs to option names, then use it to do the rendering ourselves from Python using [lxml](https://lxml.de/index.html). This is probably cleaner, although it would require backporting the fix to stable channels. It also doesn't fix problem 4, but that can also be fixed in nixpkgs.

Let me know what you think.

**Comment by jtojnar** [comment]
This somewhat overlaps with our conversion of manual to Markdown.

1. We have a pandoc filter for that that [removes the question marks](https://github.com/NixOS/nixpkgs/pull/127394) and then [another one](https://github.com/NixOS/nixpkgs/blob/2ed84aa0f2103851abfa88595a20b9b38344203b/doc/labelless-link-is-xref.lua) that converts links without label to raw docbook `xref`s. You will probably want something similar, replacing it with HTML link.
3. Opened https://github.com/jgm/pandoc/pull/7433 to add `citerefentry` support to pandoc.
4. This would be solved by converting the descriptions to Markdown, hopefully we will do that soon.

For the option name resolution, I would prefer the olinkDB but it is unclear how that will look once we get rid of DocBook completely.

But in the short term, we could just handle cross-references starting with `opt-`, which we could just resolve to whatever is after the dash. I expect that would handle majority of the links. (Submodule links would still be displayed incorrectly but they should link correctly.)

**Comment by ncfavier** [comment]
Going to close this as the last remaining problem is very minor and we're trying to move to markdown anyway
