### ISSUE TITLE
Terrible results for gtk

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixos-search#306]
If I [search for _gtk_](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=gtk), I get _gtk3-x11_ variant instead of the expected _gtk3_ package, which is nowhere to be seen. What is worse, the search shows legacy aliases like `gtk_doc` and `gnome.gtk`, which cannot be used in Nixpkgs (ofborg runs with `allowAliases=false`).

**Comment by jtojnar** [comment]
Looks like legacy aliases are actually intentionally allowed, which is bad because those should not be used:

https://github.com/NixOS/nixos-search/blob/ff8022fba5969eed3a1cc9f7ff37b868f57f805f/import-scripts/import_scripts/packages-config.nix#L3

**Comment by davidak** [comment]
gtk3 is now shown on top. is this fixed?

![Screenshot from 2021-09-22 07-58-41](https://user-images.githubusercontent.com/91113/134290797-3a24345e-6f14-4975-a4ec-f81fb2037dc5.png)

**Comment by jtojnar** [comment]
Yeah, looks okay now.
