### ISSUE TITLE
Also search in other fields

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixos-search#31]
This what the query could look like:

```
{
        "query": {
            "bool": {
                "should": [
                    {"wildcard": {"attr_name": "*nixpkgs-review*"}},
                    {"wildcard": {"name": "*nixpkgs-review*"}},
                    {"wildcard": {"homepage": "*nixpkgs-review*"}}
                ],
                "minimum_should_match" : 1,
                "boost" : 1.0
            }
        }
    }
```

It would be also useful to look in `description` and `longDescription`.

**Comment by Mic92** [comment]
The most flexible query would be `function_score` as it allows different weights between different fields. https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-function-score-query.html

**Comment by Mic92** [comment]
I found match queries with the fuzziness="AUTO" to work better:

https://gist.github.com/Mic92/6d153e5d1d21d2ce3bb4da4c03b29082#file-nixos-search-py-L46

**Comment by garbas** [comment]
wildcard search is actually quite expensive and it was done just to get the job done. I will start looking into improving query next week. Things that I plan to look at are: Ranking, Agregating on `*Packages` sets, using prefix match with a custom tokenizer would be a nice balance between usability and performance.

**Comment by Mic92** [comment]
I could imagine that a page rank over the dependency graph might work well. However the `match` query that I use in my python script should be also a good start and should fast as well since this is what elasticsearch was built for.

**Comment by Mic92** [comment]
> wildcard search is actually quite expensive and it was done just to get the job done. I will start looking into improving query next week. Things that I plan to look at are: Ranking, Agregating on `*Packages` sets, using prefix match with a custom tokenizer would be a nice balance between usability and performance.

I suppose you are using https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-suggesters-completion.html ?

**Comment by garbas** [comment]
> I suppose you are using https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-suggesters-completion.html ?

Right now `wildcard` search is [used](https://github.com/NixOS/nixos-search/blob/master/src/ElasticSearch.elm#L481) and I don't plan to work on it until I finish other issue, like #23, #33  and other smaller UI bugs. 

I wonder if it is already time to have a video call and discuss what we want in the future of this tool. Would you be interested in helping out with it? Or your interest is only to be able to search NUR packages? Which I completely understand, I'm just trying to not excluding somebody from trying to help and by assuming something.

**Comment by Mic92** [comment]
> I wonder if it is already time to have a video call and discuss what we want in the future of this tool. Would you be interested in helping out with it? Or your interest is only to be able to search NUR packages? Which I completely understand, I'm just trying to not excluding somebody from trying to help and by assuming something.

Sure my main motivation is NUR right now, but I also have some interest in building a good NixOS search, i.e. importing the database from command-not-found for indexing. I am good very good in frontend development but I had did some slightly bigger stuff with elasticsearch before.
@manveru is also working on a similar project. He was prototyping a static package index generator: https://github.com/manveru/nixdex that provides similar content as this page: https://www.archlinux.org/packages/community/x86_64/crypto++/ (Especially program dependencies)

**Comment by garbas** [comment]
Now we also search packages in other fields with boost to adjust the score. we might need to play with boost a bit to set it to correct values, but already now searching for packages gives much better results. This was done in #36 and #35 ... the rest of this work is tracked under #34 .

> > I wonder if it is already time to have a video call and discuss what we want in the future of this tool. Would you be interested in helping out with it? Or your interest is only to be able to search NUR packages? Which I completely understand, I'm just trying to not excluding somebody from trying to help and by assuming something.
> 
> Sure my main motivation is NUR right now, but I also have some interest in building a good NixOS search, i.e. importing the database from command-not-found for indexing. I am good very good in frontend development but I had did some slightly bigger stuff with elasticsearch before.

It would great to get some help and more people involved.

> @manveru is also working on a similar project. He was prototyping a static package index generator: https://github.com/manveru/nixdex that provides similar content as this page: https://www.archlinux.org/packages/community/x86_64/crypto++/ (Especially program dependencies)

Something similar I want to work on as well. At one point we can also add dependencies to the database as well and show them. Another things I want to work on is giving an overview for maintainers and which packages they maintain. A step further would be also to connect this to github issues/PRs, but one step at the time :)
