### ISSUE TITLE
Wrong package versions displayed

### ISSUE THREAD

**Issue by greghab** [NixOS/nixos-search#312]
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=freetube
- If you search for the freetube package under unstable, it says it's at `0.12.0`, but it's been [updated](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/video/freetube/default.nix#L44) 16 days ago to `0.13.0`.
- So it displays the wrong version at times.
- I believe most of the times I've noticed this, it's related to unstable packages, but don't hold me to that.

**Comment by vprigent** [comment]
Hey, just had the same happen to me with installing elixir today.
https://search.nixos.org/packages?channel=21.11&show=elixir&from=0&size=50&sort=relevance&type=packages&query=elixir
The first search result version is `1.12.3` at the time of writing, installing it outputs `installing 'elixir-1.13.4'`

**Comment by ncfavier** [comment]
That's the 21.11 channel search. You likely installed it from the unstable channel.

**Comment by ncfavier** [comment]
@greghab I suspect that our channel import was broken at the time. This shouldn't be a recurrent issue so I'm closing, but feel free to reopen if it happens again.
