### ISSUE TITLE
services.nginx.config: questionsmarks are being displayed instead of exceptions

### ISSUE THREAD

**Issue by madonius** [NixOS/nixos-search#313]
Hi, as described, in the options search page for `services.nginx.config` questionmarks are being displayed instead of exceptions this configuration is not colliding with.
See:
![image](https://user-images.githubusercontent.com/1246752/120897040-9f612c00-c624-11eb-8000-5d84553e7da5.png)

**Comment by ncfavier** [comment]
Duplicate of #303, point 1.
