### ISSUE TITLE
Index NUR packages

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixos-search#32]
Would it be possible to also import [NUR](https://github.com/nix-community/NUR)? We don't need to show search results for that on the NixOS homepage however, this would allow it to re-use nixos-search for NUR as well.
We already generate a simple [packages.json](https://github.com/nix-community/nur-search/blob/master/data/packages.json) over all repositories that can be imported. It would be great if there was a unified search that would first search nixpkgs and than fallsback to NUR in case nixpkgs does not have the package.

**Comment by garbas** [comment]
I would love to see this happen. There are few things we would need to figure out first but on a general note I'm very for this. This that concern me:

- Size and usage of our elasticsearch account. we might need to ask for bigger . Do we want to keep all "evaluations" of NUR packages? Are there also NUR options (nixos modules)?
- How to include this on the site? It is clear that searching nixpkgs is a primary goal. Should NUR be just another "channel" in the dropdown? Do we need to explain what NUR is to the visitor.

I don't have an answer for any of this yet. But this might be enough to start the conversation.

**Comment by Mic92** [comment]
1. To make it easier, we don't need to include NUR in the official search.
We could also have a separate github pages page, that provides a combined NUR + Nixpkgs search. My idea is that NUR is some sort of companion people can fallback to if nixpkgs does not have the package.

2. Scope: We have modules/overlays and home-manager modules in NUR. Right now our index only contains packages. The rest might come later.

3. Size: We only need the latest NUR evaluation. We don't have different releases. Right now we have 1212 packages (packages.json is 54kb with a lot of redundancy)

I think it's a nice addition since NUR often contains things which is hard to upstream or relatively new packages, which people just want to try out before adding to nixpkgs.

**Comment by garbas** [comment]
Having a separate index for NUR might probably be best. Probably also a separate page on search.nixos.org.

I also wonder how we will implement search going forward when flakes become a thing. do we want to search for packages in all the flakes? or only in *official* flakes.

**Comment by Mic92** [comment]
It would make sense to search other flakes. I also have not made up my mind on how to support flakes in NUR. Maybe NUR could converted to an inofficial flakes registry?

**Comment by garbas** [comment]
> Maybe NUR could converted to an inofficial flakes registry?

Maybe the registry service could also support option to also register user flakes. And NUR becomes part of this registry service.

**Comment by Mic92** [comment]
NUR is now part of the registry as of https://github.com/NixOS/flake-registry/pull/2

**Comment by garbas** [comment]
I'm closing this issue since NUR is part of the flake registry and I keep track of flake search support in #164.

Please reopen if there is any fearure that needed specific for NUR.
