### ISSUE TITLE
Add package config flags to package search

### ISSUE THREAD

**Issue by WillPower3309** [NixOS/nixos-search#325]
One thing that has been a pain point in writing overlays has been the discoverability of nix package config flags (unsure if that's the correct term for them, but I'm referring to flags like `x11Support`). Adding the ability to show which flags a package has would provide a lot of discoverability in writing overlays.

**Comment by WillPower3309** [comment]
I would be happy to investigate this myself if anyone can give me a small push in the right direction

**Comment by ysndr** [comment]
Hej, I'm afraid this is a bit out of scope, as we're evaluating the functions that take those flags into derivation attrsets. The way it works now doesn't give insight in what flags can be used.
