### ISSUE TITLE
Update package config

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#337]
@garbas can you update your package config to be in sync with https://github.com/NixOS/nixpkgs/pull/113713, so we have `emacsPackages` in the search again?

And maybe you can propose a change so the `emacsPackages` appear as `emacs.pkgs` as they should after https://github.com/NixOS/nixpkgs/pull/107152. Here is an issue for that: https://github.com/NixOS/nixpkgs/issues/134672

**Comment by sternenseemann** [comment]
#405
