### ISSUE TITLE
Bug: When opening the source package. It turns out a patch from /nix/store/

### ISSUE THREAD

**Issue by dan4ik605743** [NixOS/nixos-search#339]
![image](https://user-images.githubusercontent.com/86075850/130191429-467d136a-8b66-4987-89c3-77615eb10826.png)
![image](https://user-images.githubusercontent.com/86075850/130191545-171bae07-a00a-4007-b664-6cac0c91122c.png)
We take absolutely any package and press source. We get Page not Found, and in the links 
https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable//nix/store/gih766jr8d6rcdp30sm5gn93sqcfvapp-source/pkgs/applications/networking/instant-messengers/vk-cli/default.nix#L48
is visible patch from /nix/store. Noticed it not long ago, about somewhere a week ago. And it is so with all channels.

**Comment by dan4ik605743** [comment]
![image](https://user-images.githubusercontent.com/86075850/130192066-fc68e3de-c79f-4c04-8355-e41b14cc3b61.png)
https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/applications/networking/instant-messengers/vk-cli/default.nix#L48

**Comment by ysndr** [comment]
I think this has been reported already in #335 and will be fixed once #324 lands.
The bug is a regression from rewriting the indexer in #320.

**Comment by dan4ik605743** [comment]
Well, then I close the issue.
