### ISSUE TITLE
Improve search quality / UX

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-search#34]
- [x] no expensive wildcard, #35 
- [x] ranking, #36
- [ ] suggestions / completion suggesters, #74 
- [ ] facet search, aggregation (grouping of package sets)

**Comment by davidak** [comment]
Does "suggestions" mean showing them while i type? Or above the results as "Do you mean ..."?

I really like how responsive this implementation is: https://trailingwhite.space/nix-package-search/

https://functional.cafe/@philipwhite/104009531564051145

**Comment by garbas** [comment]
I think it can be both or either. It is something we can explore going forward.

The example you point to loads all of the channel in the browser and that is why this is possible. You can see [his reponse](https://functional.cafe/@philipwhite/104241407403351376). If we want to support multiple evaluations per channel (which i think we want) then we need such thing as elasticsearch. Also going with his approach we would have to implement things like ranking and aggregation our self. Try searching for "ghc" and see which search gives you more relevant result.

**Comment by davidak** [comment]
I think ES might not be *needed*, but gives a lot of options for nice to have features, which will improve UX. I'm fully for ES!

Like https://discourse.nixos.org/t/concept-use-any-package-version/6515

**Comment by garbas** [comment]
Closing this issue since it is mostly done except the faceted search and that already has its own ticket https://github.com/NixOS/nixos-search/issues/163
