### ISSUE TITLE
attribute sets and lists are displayed in a wrong format

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixos-search#351]
**Describe the issue**
On https://search.nixos.org/options, one can search for NixOS-options.
Unfortunately, attribute sets and lists are displayed in a wrong way:
- correct would be: `[{ key = "value"; key2 = "value2";} {...}]`
- on website/wrong: `[{ "key": "value", "key2": "value2"}, {...}]`
  (errors: quotes around keys / : instead of = / , instead of ; / no ; at end of each option / , instead of space between items)

If copy-n-pasted to the config-file, nix reports syntax errors.

**Page links**
- https://search.nixos.org/options
- e.g. https://search.nixos.org/options?channel=21.05&show=services.xserver.xrandrHeads&from=0&size=50&sort=relevance&query=xrandr, but also many others / probably all lists and attribute sets

**Comment by tfc** [comment]
Some colleagues reported the options search as a source of frustration after they stepped on the same problem: copy&pasting something from official nixos pages and have it not working.

![Screenshot from 2021-09-04 10-43-15](https://user-images.githubusercontent.com/29044/132088653-ceab2ea1-febd-41e3-9b17-28b6bf5c9383.png)

see the commas in the list on the screenshot in the "examples" section.

i tried to fix it and have found this code line where the content is json-decoded: https://github.com/NixOS/nixos-search/blob/main/src/Page/Options.elm#L407


It seems like there should be a function like nix's `builtins.fromJSON`.
Unfortunately, my elm knowledge is too limited to quickly come up with the right implementation
