### ISSUE TITLE
Server returned 404 on flakes search

### ISSUE THREAD

**Issue by tad-lispy** [NixOS/nixos-search#362]
When searching for flakes I'm getting this:

![Screenshot from 2021-09-17 12-50-24](https://user-images.githubusercontent.com/1684495/133770954-6c57f612-cf4a-4dd3-a747-5909cc577556.png)

E.g. https://search.nixos.org/flakes?channel=21.05&from=0&size=50&sort=relevance&type=packages&query=libreoffice but it's the same for every query.

Looks like `POST | https://nixos-search-5886075189.us-east-1.bonsaisearch.net/latest-23-group-manual/_search` is failing.

**Comment by ysndr** [comment]
Yes this is a known issue! Flake import is currently broken due to sops-nix (#361, #358)
