### ISSUE TITLE
Missing version attribute

### ISSUE THREAD

**Issue by felixsinger** [NixOS/nixos-search#367]
The version attribute is missing for the `coreboot-toolchain` package. https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=coreboot-toolchain

**Comment by felixsinger** [comment]
So, I fixed the issue with the name attribute, and since then the package also got some other patches, but the version attribute is not appearing on the website.

**Comment by samueldr** [comment]
Indexing might have had unrelated issues. I couldn't say for sure.
