### ISSUE TITLE
examples formatting is wrong

### ISSUE THREAD

**Issue by evils** [NixOS/nixos-search#369]
using telegraf as an example,
source code:
![image](https://user-images.githubusercontent.com/30512529/137592011-2cfc39de-fdc5-437c-8980-aac062cf6faa.png)
man page:
![image](https://user-images.githubusercontent.com/30512529/137592036-5fd0f2f2-0133-44a1-9c7f-4c5f1a3cd379.png)
web page:
![image](https://user-images.githubusercontent.com/30512529/137592048-77c318ff-975c-4d01-9099-ae7dd1b42569.png)

programs.git.config is similarly affected
i suspect it's being formatted as json, regardless of the source type

**Comment by TheSirC** [comment]
You are totally right : this is a duplicate of #351 and #233

I hope it will get fixed soon : having examples that look kind of Nix but are not Nix is hellish way to loose a bunch of times in debugging...

**Comment by Linerre** [comment]
Hi All,

Thanks for your effort. I just found yet another such case when configuring `tlp` pkg. 


    {
        "TLP_DEFAULT_MODE": "BAT",
        "OPTION2": "VALUE"
     }

shoud really be


    {
        "TLP_DEFAULT_MODE" = "BAT";
        "OPTION2" = "VALUE";
    }

see https://search.nixos.org/options?channel=21.05&show=services.tlp.settings&from=0&size=50&sort=relevance&type=packages&query=tlp

**Comment by evils** [comment]
closing in favour of  351 (it has a PR that claims to fix this)
