### ISSUE TITLE
a way to see what outputs a package has

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixos-search#375]
Would help with cases such as https://github.com/NixOS/nixpkgs/issues/147215

**Comment by googleson78** [comment]
Duplicate of #302

**Comment by ncfavier** [comment]
This was done in https://github.com/NixOS/nixos-search/pull/419, I forgot to search for other open issues :)

**Comment by ncfavier** [comment]
Also note https://github.com/NixOS/nixos-search/pull/452
