### ISSUE TITLE
flake-info: Unhelpful error message on invalid XML

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixos-search#381]
When encountering invalid XML in option descriptions, `flake-info` fails with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: exit_code: Some(44)stdout: stderr: Invalid XML:
6:1 (224)-6:8 (231): Expected end element for: Name {nameLocalName = "service", nameNamespace = Nothing, namePrefix = Nothing}, but received: EventEndElement (Name {nameLocalName = "para", nameNamespace = Nothing, namePrefix = Nothing})
', src/data/export.rs:318:43
```
Could you show which option contains the faulty description? This would greatly simplify debugging.

cc @ysndr

**Comment by ysndr** [comment]
It stems from an ill formatted documentation field.
We should be more clear about it and maybe not panic either.

You can check out #382 to see if the issue is resolved
