### ISSUE TITLE
`flake-info` output is printed to stderr

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixos-search#384]
The output should be printed to `stdout`, so that regular output can be distinguished from error output.

I'd like to silently run `flake-info` as part of my flake's test suite, but `flake-info flake ... 2>/dev/null` suppresses all errors.

Maybe we could also add a `--check` mode, which skips all output and only checks if `flake-info` would run successfully.

**Comment by ysndr** [comment]
flake-info does not really have any output
The internal structure printed during the run is part of badly handled debugging, all the rest is logs which can be tweaked using RUST_LOG

there is output if the `--json` flag is given which prints elastic compatible json
Arguably, errors could be printed to stdout but don't contain data so Im hesitant

**Comment by ysndr** [comment]
Running without arguments should be equal to a `check` argument as it doesn't do anything with the queried data but passes all transformation steps

**Comment by erikarvstedt** [comment]
> The internal structure printed during the run is part of badly handled debugging

Then printing the structure to `stdout` should be removed.

> errors could be printed to stdout 

No, errors should always be printed to `stderr`.
