### ISSUE TITLE
`literalExpression`s are displayed as string literals

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixos-search#388]
`literalExpression "expr"` is displayed as `"expr"` instead of `expr`. 
Example: Default value of [`networking.fqdn`](https://search.nixos.org/options?channel=unstable&show=networking.fqdn&from=0&size=30&sort=relevance&type=packages&query=networking.fqdn).

cc @ncfavier @ysndr

**Comment by ncfavier** [comment]
@ysndr for reference, here's the Nix pretty-printer in Python we had before the Rust rewrite:

https://github.com/NixOS/nixos-search/blob/f866edd1cfc3e0f68cd0ad314b09b3d0ae1a6ce0/import-scripts/import_scripts/nix.py

Not sure how you want to go about this.

**Comment by ysndr** [comment]
Thank you
I think its an issue of parsing the expression type though. I'm on it after the weekend!

**Comment by ncfavier** [comment]
Ignore my previous comment, brainfart.

**Comment by ncfavier** [comment]
So the first step is to stop treating `literal*` specially in `flake_info.nix` so that the information is available in the produced JSON. Then we can handle `literalExpression`/`literalExample` e.g. in the pretty-printer by just returning `o["text"]`, and `literalDocBook` in `export.rs` using pandoc.

**Comment by ysndr** [comment]
I got a bit confused here by the structure of your sentence..
Anyway, @ncfavier and @erikarvstedt feel free to check out

https://61c5f09cfa1ce4b942596b58--nixos-search.netlify.app

This should fix this issue

**Comment by ncfavier** [comment]
Don't worry about it 😅 what you have implemented now is probably better than what I was trying to formulate anyway.

**Comment by ysndr** [comment]
Fixed in #395
