### ISSUE TITLE
Search action no longer runs successfully

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixos-search#389]
See github action error: https://github.com/NixOS/nixos-search/runs/4521001235?check_suite_focus=true

**Comment by ysndr** [comment]
Thanks, I am on it

**Comment by ysndr** [comment]
It is because the maintainer of `gotypist` did not add themselves to the maintainers.nix file but instead wrote is name as a string, which is unexpected to nix-flakes

**Comment by pb-** [comment]
@ysndr Sorry about that, I didn't realize that a string was unacceptable :see_no_evil: . Thank you for fixing it.

**Comment by ysndr** [comment]
Thats alright, its been overlooked during review everything is alright.
The action wont succeed until there is an updated nixos-unstable with that change included, lets see when that is going to land.

**Comment by ysndr** [comment]
Worked around in #393
