### ISSUE TITLE
Attribute keys are not quoted properly

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixos-search#392]
Just tracking the issue mentioned [here](https://github.com/NixOS/nixos-search/pull/357#issuecomment-936935297): attribute keys in examples/defaults containing spaces are not quoted properly (e.g. [services.netatalk.settings](https://search.nixos.org/options?channel=unstable&show=services.netatalk.settings&from=0&size=50&sort=alpha_asc&type=packages&query=services.netatalk.settings)).

**Comment by ysndr** [comment]
Ahh that’s difficult though
I think I can’t tell from the input whether things are quoted or not
But we can do some heuristics whether they should be or not (ie contains spaces or special characters) perhaps

**Comment by ncfavier** [comment]
Just mimic the nixpkgs lib: https://github.com/NixOS/nixpkgs/blob/master/lib/strings.nix#L360

**Comment by ncfavier** [comment]
Closed by #396
