### ISSUE TITLE
Internal links don't cause the page to change

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixos-search#403]
As mentioned in https://github.com/NixOS/nixos-search/pull/402#issuecomment-1003262899, when clicking a link in an option description to a search.nixos.org page, like [here](https://search.nixos.org/options?channel=unstable&show=environment.profileRelativeSessionVariables&from=0&size=50&sort=alpha_asc&type=packages&query=environment.profileRelativeSessionVariables), the URL bar changes but the page doesn't (in both Firefox and Chromium).

@garbas do you know how to fix this?

As a temporary workaround I suggest we add `target=_blank` to those links.

**Comment by garbas** [comment]
@ncfavier Sorry for slow response time. I took some break over the holidays. But I see @ysndr fixed it :heart: !

**Comment by ncfavier** [comment]
No worries!
