### ISSUE TITLE
Clicking On non-NixOS on any package on webpage doesnt have any effect

### ISSUE THREAD

**Issue by aaftre** [NixOS/nixos-search#409]
Previously clicking "On non-NixOS" tab would show install command for non-nixos environment for any package. Seems to just reload the page now.

**Comment by samueldr** [comment]
I can reproduce.

I suspect the recent URL handling changes, maybe?

**Comment by ncfavier** [comment]
Probably. cc @ysndr

**Comment by ncfavier** [comment]
We can probably keep the old matching behaviour for `Packages` models and the new one for `Options` models, unless there's a cleaner solution.

**Comment by ncfavier** [comment]
I think the proper solution for this would be to turn cross-references into special links that only change the `query` and the `show`. That way we can keep the shallow matching and we also solve the issue of every channel linking to `unstable`.

**Comment by ysndr** [comment]
Yes we should have non navigating links/actions but for now I have to exclude allnon navigating changes to the model separately, which is a bit annoying but I'm not sure where to abstract over this.

**Comment by ncfavier** [comment]
I was suggesting earlier just reverting to `(Packages _, Packages _) -> True` since packages aren't linking to each other

**Comment by ncfavier** [comment]
Or you could explicitly pick which fields to include instead of which fields to exclude.
