### ISSUE TITLE
Document how to generate the "big numbers" for a NixOS Release

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixos-search#413]
The 21.11 release announcement lacked the nixos option and nixpkgs package deltas.

Would be great to document the process of getting these numbers, as well as provide many individuals who are about to get access to the elastic search data.

**Comment by garbas** [comment]
There was a script in previous python import-script that was doing this.

@ysndr Do you maybe have an idea how could we bring it back?

**Comment by ysndr** [comment]
QnD way: diff of unique elements in index for 21.11 - 21.05?

haven't tested but

```
OLD=$(flake-info --json --kind package nixpkgs 21.05 | | jq '. | length' )
NEW=$(flake-info --json --kind package nixpkgs 21.11 | | jq '. | length' )

echo  $NEW - $OLD
```

could work

**Comment by dasJ** [comment]
This is part of the release wiki now: https://nixos.github.io/release-wiki/Final-Release.html
