### ISSUE TITLE
Show .dev sub-packages in search

### ISSUE THREAD

**Issue by kvark** [NixOS/nixos-search#414]
**Introduce your stance**
Was trying to figure out why xcbutilkeysyms doesn't register itself in pkg-config. Thought it could be a package issue, but then discovered that "xcbutilkeysyms.dev" contains the pkg-config script. Was confused as to why https://search.nixos.org/ didn't show the dev package to me.

**Describe the issue**
Dev sub-packages are a bit of a magic. It would be great if https://search.nixos.org/ assisted in discovering them.

**Page links**
https://search.nixos.org/packages?channel=21.11&show=xorg.xcbutilkeysyms&from=0&size=50&sort=relevance&type=packages&query=xcbutilkeysyms

**Additional context**

**Comment by ncfavier** [comment]
Technically speaking that's not a package, it's an *output* of the `xcbutilkeysyms` package. In particular it shares all of its metadata, so I don't think it should be listed separately. We could display the outputs for each package though (maybe unless there's only `out`), flake-info already exports a `package_outputs` field so this should only require a change to the frontend.

**Comment by kvark** [comment]
Something doesn't match up. If it's just one of the outputs, I'd expect `xcbutilkeysyms` to work as a superset of `xcbutilkeysyms.dev`. But in my case I think `xcbutilkeysyms.dev` contained things not included in `xcbutilkeysyms` (the pkg-config stuff).

**Comment by ncfavier** [comment]
`xcbutilkeysyms` refers to the default `out` output. Outputs are separate directories and need not be included in one another. See https://nixos.org/manual/nixpkgs/unstable/#chap-multiple-output

**Comment by ysndr** [comment]
An additional problem is that even if we list the outputs, it's not clear what these include. In fact derivation authors could add outputs for anything and even a dev output doesn't imply specific contents.

**Comment by ncfavier** [comment]
Ah, it's not as simple as I thought because `nix-env -qa` doesn't expose `outputs`, only `meta.outputsToInstall`. We'd need to find another way to get a flat list of nixpkgs packages.

**Comment by ncfavier** [comment]
Actually this is fixed in Nix 2.6! https://github.com/NixOS/nix/pull/5878
