### ISSUE TITLE
Clarity in Header Buttons

### ISSUE THREAD

**Issue by ghost** [NixOS/nixos-search#426]
At least one of my friends was completely under the impression that the "options" button at the top of the search was to *configure the search tool*.

It may be useful to add extra clarity, IE naming the header bars "Nix Packages", "Nix Options", "Nix Flakes". That may seem redundant, but it would probably reduce friction to people's early Nix usage.

**Comment by Massolari** [comment]
It seems a good "First issue"
Can I open a PR for this?

**Comment by ncfavier** [comment]
Feel free. I would prefer only changing "Options" to "NixOS options" and leaving the other two unchanged.
