### ISSUE TITLE
Elasticsearch export failing

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixos-search#431]
https://github.com/NixOS/nixos-search/runs/5344749187?check_suite_focus=true

ping @ysndr as I have no clue what's going on

**Comment by ncfavier** [comment]
Ah, now the nixpkgs export is failing too with the same error. Maybe we need to garbage collect previous indexes?

ping @garbas

**Comment by ysndr** [comment]
Yes looks like the elastic search space is running out.
I cant really do anything, but ping again on matrix.
Thank you for reporting

**Comment by garbas** [comment]
@ncfavier @ysndr thank you for reporting. 

It doesn't look like we are running out of space 
![2022-02-27-230911_1564x625_scrot](https://user-images.githubusercontent.com/20208/155902008-b62f0941-ad3f-475e-af67-0f1bb5921286.png)

But just in case i'm going to garbage collect old indexes

**Comment by garbas** [comment]
I've removed all indices with version 25 and lower.

**Comment by ncfavier** [comment]
I just triggered a workflow, let's see how it goes

**Comment by ncfavier** [comment]
Seems to work now
