### ISSUE TITLE
Make deployments less noisy

### ISSUE THREAD

**Issue by ysndr** [NixOS/nixos-search#434]
Each netlify deployment currently comments on both the commit as Wel as the PR aside from also leveraging deployments.
I think we should either enable obmverriding the PR comment or disable comments altogether since github already provides links to the deployment in a less intrusive way.

**Comment by garbas** [comment]
If I'm not mistaking this was fixed now. Please reopen if I'm wrong.

**Comment by ncfavier** [comment]
It's still very noisy, and I get notifications for commits like https://github.com/NixOS/nixos-search/commit/3df8b7b165e8ee1a7c5957153e049a36f7c9c7f0#commitcomment-71737881 that aren't even on a branch. I am in favour of overriding PR comments, and disabling commenting on commits.
