### ISSUE TITLE
Following links does not reset the `from` parameter in the URL

### ISSUE THREAD

**Issue by RasmusRendal** [NixOS/nixos-search#490]
Steps to reproduce:
1. [Search for `services.xserver` in `unstable`, and navigate to the second page of results](https://search.nixos.org/options?channel=unstable&show=services.xserver.windowManager.default&from=50&size=50&sort=relevance&type=packages&query=services.xserver).
2. In `services.xserver.windowManager.default`, it suggests that you use `services.xserver.displayManager.defaultSession` instead
3. Click the link. If you open in a new tab, the issue does not appear
4. You get the following screen, where you have to click "First" or "Previous" to get to `services.xserver.displayManager.defaultSession`:

![bug](https://user-images.githubusercontent.com/19538856/172779451-0cbd927b-e483-40dc-9deb-b513166725d6.png)

Expected result:

Clicking a link for a new search should take me to the first page of results

**Comment by ncfavier** [comment]
I see two possible solutions:
1. add `&from=0` to all option xref links
2. make `Search.init` not default to the previous model's from and size

@ysndr thoughts?

**Comment by ysndr** [comment]
Yes i think the right behaviour would be to reset `from` to 1 (or zero if we have no results) when the query changes
