### ISSUE TITLE
UX: Easier to select package name in browser

### ISSUE THREAD

**Issue by CreativeCactus** [NixOS/nixos-search#496]
It would be nice if when double-click-then-dragging (or just double-clicking, for packages without a dash in the name) did not select `Version`.

![image](https://user-images.githubusercontent.com/12624092/177049331-b693147a-ecdb-4e3f-9fe6-7374dacea11e.png)

Adding a `&nbsp;` or even a zero width space after the package name should fix this without the need for javascript.
For those with JS enabled it might be nice to show a little "copied" mark when clicking on the package name.

I think the solution is best implemented [here](https://github.com/NixOS/nixos-search/blob/eea6cd3ffb4d3d39956316d6e976b9d5ce52d508/frontend/src/Page/Packages.elm#L352), but I don't know elm or the context well.

**Comment by ncfavier** [comment]
Seems like a Chrome/Chromium bug, I can't reproduce on Firefox.

I think the best solution would be to use `user-select: all;` on the `<code>` element. That way when you click the name it highlights the entire name (and nothing else), but you still need to copy manually (I think the JS "click to copy" thing is a bit intrusive).
