### ISSUE TITLE
packages: Offer more installation method suggestions and discourage `nix-env -i`

### ISSUE THREAD

**Issue by roberth** [NixOS/nixos-search#508]
Currently the package details only suggest `nix-env`.

`nix-env` is considered bad practice by many, so we should at least offer better, declarative and/or non-global installation methods in the packages search details.

 - NixOS `environment.systemPackages`
 - home-manager
 - package or nix-shell
    - with `callPackage`
    - with `pkgs`
    - as `nativeBuildInputs`
    - as `buildInputs`

This also solves the problem in docs and conversations of having to explain the general idea of "package installation" over and over again, which involves either a roundtrip to ask what sort of installation they need (might not even be clear) or, in the case of docs, trying to explain multiple methods.
Knowing the attribute path also means that we can show relevant instructions for dealing with nested attributes in `callPackages`.

Related: https://github.com/NixOS/nixos-search/issues/506#issuecomment-1197073259

**Comment by fricklerhandwerk** [comment]
Also `nix-shell -p`.

I fully agree `nix-env` should not be the first or only suggestion. Presenting all these options would need a different UI, e.g. a link to a page listing all the options and linking to a tutorial piece for details.

See [`nix-versions`](https://github.com/lazamar/nix-package-versions) for an [example](https://lazamar.co.uk/nix-versions/?package=hello&version=2.12&fullName=hello-2.12&keyName=hello&revision=bf972dc380f36a3bf83db052380e55f0eaa7dcb6&channel=nixpkgs-unstable#instructions).
It also [shows `nix-env` first](https://github.com/lazamar/nix-package-versions/blob/419b52afc3fabcc3d84d132037d106ad929a5d33/src/App/Server.hs#L276-L308).

**Comment by roberth** [comment]
> Presenting all these options would need a different UI

Presentation of the search results is handled by a single page application written in Elm. It is already set up to display multiple tabs with an installation method in each of them.
I don't see much of a _technical_ reason to build a new kind of page, but it would be nice to have a page that displays only a single package. Linking to the search results can be a bit noisy, both in the url and on screen.

**Comment by fricklerhandwerk** [comment]
Ah, I missed that tab thingy. In that case, great.
