### ISSUE TITLE
Search result issues

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#51]
The first thing i tested already fails:

https://search.nixos.org/options?query=bees&from=0&size=15&channel=unstable

this is what should be found:

https://nixos.org/nixos/options.html#bees

and then try to search for "beesd". Nothing is found anymore!

When you found the option you need, you want to copy them next. That also fails! https://peertube.social/videos/watch/9d1ccb0c-9811-4107-aece-fa2648c0b213

Haven't tested more yet, but there might be more issues.

**Comment by garbas** [comment]
we haven't yet put any work on options search apart from doing a basic wilcards search. this will come before we replace current search.
