### ISSUE TITLE
Some links to nixos options contain ``nixos/modules/`` twice

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nixos-search#513]
For example: https://search.nixos.org/options?channel=unstable&show=environment.shells&from=0&size=50&sort=relevance&type=packages&query=environment.shells

has ``Declared in nixos/modules/nixos/modules/config/shells-environment.nix`` which links to https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/nixos/modules/config/shells-environment.nix 

The correct name would be ``nixos/modules/config/shells-environment.nix`` and link https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/config/shells-environment.nix

**Comment by ncfavier** [comment]
Not a nixos-search issue: this issue also appears in the upstream `options.json`. First bad commit is https://github.com/NixOS/nixpkgs/commit/52b0ad17e3727fe0c3ca028787128ede5fb86352

**Comment by ncfavier** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/185056#issuecomment-1206572049
