### ISSUE TITLE
IPv6 support of search backend

### ISSUE THREAD

**Issue by andir** [NixOS/nixos-search#52]
Hate to bring it up again but the backend we are using for the search doesn't seem to support IPv6. While Elasticsearch is perfectly capable of IPv6 the host (despite being on AWS) failed to enable it. This is a discrimination against people with poor (or none) IPv4 connectivity on this planet.

Like explained in my [NixOS.org Netlify post](https://discourse.nixos.org/t/announcement-moving-nixos-org-to-netlify/6212/2) we should try to have this as a baseline requirement for new services that will - to some degree - be mandatory/required to interacting with our services/websites.

**Comment by garbas** [comment]
I will ask if our ES provider can support IPv6.

I know your :heart: is in the right place, but I would like to avoid such strong wording as *"This is a discrimination ..."*. It *might* be understood wrong depending on the context. I was also guilty of such mistakes in the past and I just hope I will not make them in the future.

**Comment by mweinelt** [comment]
Just so other people can find this using the GitHub search. I just got bitten by that.

> Network Error!
> A network request bonsaisearch.net domain failed. This is either due to a content blocker or a networking issue.

**Comment by samueldr** [comment]
This is an accessibility issue. Accessibility is not only about "handicaps".

The search cannot ship if it's not IPv6 enabled, plain and simple. Some environments won't go through IPv4, as can be seen here by @mweinelt (I suppose), which means that some *technically inclined people*, you know, the kind of people a Linux distro, or a package manager caters for, will have an issue that is mostly out of their control for the site.

This is, I believe, not something that we can just program our way out of, so I think this'll need to be validated with the upstream provider.

**Comment by grahamc** [comment]
Perhaps it is something we could fix with a ipv6 capable proxy if upstream isn't able to support ipv6 directly.

**Comment by garbas** [comment]
Ipv6 is a blocker, as it wasn't for nixos.org. It is important thing definitely, but not a blocker.

**Comment by garbas** [comment]
I also reminded bonsai.io to answer the questions regarding ipv6 support, since they didn't answer.

**Comment by andir** [comment]
> Regardless of their decision we should move forward and not _punish_ all of the users. Punish is probably to strong of a word, but can not think of a better one.

Punish? What do you mean? We've been living with this solution for years now and it *just* works. It has different problems but none that make it unusable.

**Comment by DearRude** [comment]
Any updates on this?

**Comment by f2k1de** [comment]
Still the same problem… When will this be fixed?

Also `This is either due to a content blocker or a networking issue.` is not true: It's not a content blocker or a fault in the network, it's a problem at bonsaisearch.

**Comment by ncfavier** [comment]
Right about [now](https://github.com/NixOS/nixos-search/pull/656). Can someone double-check that PR?
