### ISSUE TITLE
Feature request: Make use of rust conditional compilation [feature]

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixos-search#523]
When using flake-info as a dependency, lots of dependencies are included in the lib that the user might not want. Most notably, uploading to elasticsearch is unnecessary for me and has a lot of dependencies.

Rust has the possibility to use conditional compilation using `{features = [...] }` in the `Cargo.toml` (see [doc](https://doc.rust-lang.org/cargo/reference/features.html)).

**Comment by ysndr** [comment]
I'm aware of conditional compilation.
It should be relatively straight forward to `cfg!` the eleastic part out of the pipeline.
I'm happy to review if you give a shot at it or look at it myself when i find time for it

**Comment by ysndr** [comment]
Are you mainly interested in using the lib only?

**Comment by ysndr** [comment]
@LoveIsGrief does this solve your issue?

**Comment by LoveIsGrief** [comment]
That was faster than I expected!  Indeed, I can now compile without having `gcc` or `openssl-dev` installed. The other build errors I can blame on my bad code :yum:  Thank you!

It was necessary to pin it to a commit though since there are no tags and the version number stayed the same. Is that intentional?

**Comment by ysndr** [comment]
This project was never prepared to be released as a library hence we don't have proper versioning for the library in place yet.
Now there seems to be at least some interest, so maybe we have to rethink that.

**Comment by LoveIsGrief** [comment]
That would be a nice addition indeed :+1:
