### ISSUE TITLE
Options search doesn't match option prefixes

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixos-search#537]
[extradep](https://search.nixos.org/options?channel=unstable&from=0&size=30&sort=relevance&type=packages&query=extradep) and [extraDep](https://search.nixos.org/options?channel=unstable&from=0&size=30&sort=relevance&type=packages&query=extraDep) should match `system.extraDependencies`, but they don't.
The [full option string](https://search.nixos.org/options?channel=unstable&from=0&size=30&sort=relevance&type=packages&query=extradependencies) matches correctly.

**Comment by erikarvstedt** [comment]
Not fixed.
[extradependencies](https://search.nixos.org/options?query=extradependencies&from=0&size=30&sort=relevance&channel=unstable) matches, but [extradep](https://search.nixos.org/options?channel=unstable&from=0&size=30&sort=relevance&type=packages&query=extradep) doesn't.

**Comment by ncfavier** [comment]
Hopefully when the 7.10 update lands we can use the case_insensitive option and fix this.
