### ISSUE TITLE
Searching packages does not work

### ISSUE THREAD

**Issue by Matt-DESTROYER** [NixOS/nixos-search#546]
Searching for a package results in this error repeated continuously:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at r (main-78cfeacd4b04d48f70be.js:1:26482)
    at r (main-78cfeacd4b04d48f70be.js:1:26572)
    at r (main-78cfeacd4b04d48f70be.js:1:26572)
    at Rn (main-78cfeacd4b04d48f70be.js:1:26636)
    at Cn (main-78cfeacd4b04d48f70be.js:1:26698)
    at main-78cfeacd4b04d48f70be.js:1:28559
    at e (main-78cfeacd4b04d48f70be.js:1:28850)
```

**Comment by ncfavier** [comment]
Can't reproduce. Can you try with a different browser?

**Comment by Matt-DESTROYER** [comment]
There doesn't seem to be any issue in Microsoft Edge, Internet Explorer has a different error. Google Chrome results in the error above.

**Comment by ncfavier** [comment]
Chromium works fine for me.

**Comment by ncfavier** [comment]
https://discourse.elm-lang.org/t/javascript-exception-cannot-read-property-childnodes-of-undefined-with-extension-dark-reader/2748 suggests a browser extension might be causing this; could you try again with all extensions disabled?

**Comment by Matt-DESTROYER** [comment]
Huh, that's very weird, you're right, thanks :D

**Comment by mhqmarques** [comment]
Thanks a lot.. 

> https://discourse.elm-lang.org/t/javascript-exception-cannot-read-property-childnodes-of-undefined-with-extension-dark-reader/2748 suggests a browser extension might be causing this; could you try again with all extensions disabled?

Thank you very much... it helped me a lot
