### ISSUE TITLE
Import failing due to reached ElasticSearch limit

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixos-search#548]
Most of the VSCode extensions that I maintained are having an outdated version number in the search that does not correspond to what was merged.

[`vscode-extensions.davidanson.vscode-markdownlint`](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=vscode-extensions.davidanson.vscode-markdownlint) for example shows as `0.47.0` in both `22.05` and `unstable` channels but it should show `0.48.1` as the change was [merged](https://nixpk.gs/pr-tracker.html?pr=194718) (https://github.com/NixOS/nixpkgs/pull/194718) and [backported](https://nixpk.gs/pr-tracker.html?pr=195381) (https://github.com/NixOS/nixpkgs/pull/195381) few days ago.

**Comment by ncfavier** [comment]
Seems like we've [hit](https://github.com/NixOS/nixos-search/actions/runs/3263420360/jobs/5362206881#step:4:184) a size limit on the ElasticSearch instance:

> Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [3000]/[3000] maximum shards open

cc @garbas

**Comment by garbas** [comment]
I'm removing old indexes. Will take some time before cleanup is done. I'll manually rerun the last import workflow

I think there are few things we could do to improve this situation in the future (we should probably open separate issues).

- report on marketing matrix channel when things fail to import on a daily GitHub workflow

- have a garbage collection GitHub workflow which would remove older indexes (the ones with version older the what is in main)

**Comment by garbas** [comment]
And @ncfavier thank you for pinging me

**Comment by garbas** [comment]
I've removed the majority of indexes and hourly imports are working again.

> Is there maybe a way to tweak the retention policy on ElasticSearch directly?

There is nothing really to tweak since we are using the managed ES.
