### ISSUE TITLE
Links from the homepage to search are broken

### ISSUE THREAD

**Issue by raindev** [NixOS/nixos-search#558]
**Introduce your stance**

Currently the links to search on nixos.org are broken, resulting in an HTTP 404:

![image](https://user-images.githubusercontent.com/4586410/199846287-1f365ea6-ca59-4259-8785-065fde586bae.png)

**Describe the issue**

The top menu search entry ("magnifying glass") links to https://search.nixos.org/packages, which results in a 404 Not Found page.

Similarly 'Search for a package' also results in a 404, e.g. https://search.nixos.org/packages?query=hello

**Page links**

https://search.nixos.org/packages

**Additional context**

Navigating to https://search.nixos.org produces a 304 redirect to https://search.nixos.org/packages, no idea why direct link doesn't work.

**Comment by garbas** [comment]
This was fixed in #557

**Comment by raindev** [comment]
Great! :clap:
