### ISSUE TITLE
Packages' homepage can be empty

### ISSUE THREAD

**Issue by aiotter** [NixOS/nixos-search#571]
I found `nixpkgs#yarn2nix`'s `meta.homepage` is `""`. ([source](https://github.com/NixOS/nixpkgs/blob/cf63ade6f74bbc9d2a017290f1b2e33e8fbfa70a/pkgs/development/tools/yarn2nix-moretea/yarn2nix/default.nix#L380))

When you search `yarn2nix`, the HTML tag corresponding to the Homepage link is `<a href target="_blank">🌐 Homepage</a>`.
It seems this project does not expect `meta.homepage = ""`. ([source](https://github.com/NixOS/nixos-search/blob/f249d4964e38b13f32e25634145e06853db41657/frontend/src/Page/Packages.elm#L1028-L1039))
Is this an expected behaviour?

FYR this issue is at first reported on raycast/extensions#3594.

**Comment by ncfavier** [comment]
If a package has no homepage, it should not have a `homepage` field. `mkYarnPackage` should be fixed.

(That code looks nonsensical anyway: is `packageJSON` supposed to be a path or an attribute set?)

**Comment by aiotter** [comment]
I agree with you. Should I create an issue on their repo and close this one?

**Comment by ncfavier** [comment]
I've opened a PR: https://github.com/NixOS/nixpkgs/pull/202328

I think this issue can be closed.

**Comment by aiotter** [comment]
Nice work! Closing👍
