### ISSUE TITLE
Improve search for common words such as `make`

### ISSUE THREAD

**Issue by roberth** [NixOS/nixos-search#577]
**Introduce your stance**

Package search should be accessible to beginners.

**Describe the issue**

I've [answered](https://stackoverflow.com/questions/74649163/how-to-install-the-make-command-in-nixos?noredirect=1#comment131787556_74649163) a beginner question, and they couldn't find `gnumake`.

> > Did you try [search.nixos.org/packages](https://search.nixos.org/packages)?
> @ RobertHensing Yes . I've writing make. The only result was ekam

It seems that they were puzzled by the cluttered list of results that comes up for `make`.

I propose three solutions:
1. Return a compact list of package names when the number of results is >1
2. Index the names of binaries, and assign a lot of weight to those keywords. This will probably make `gnumake` float to the top, and make some commands easier to find (e.g. `host`, `mv`, `initdb`)
3. Create a list of hardcoded first results to always include at the top. (might not be as easy to implement and requires more manual work. more of a last resort)

**Page links**

make
https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=make

initdb (postgresql)
https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=initdb

**Additional context**

- [ ] I already created a Pull Request

**Comment by ncfavier** [comment]
I like idea 2. We could use [nix-index](https://github.com/bennofs/nix-index) for this:

- after running `nix-env`, generate the file database with `nix-index` (takes about 5 minutes so this would ~double the nixpkgs import time)
	- note: would be nice to abort the import early in CI if the index for this revision already exists, so that we don't do ~3*10 minutes of useless computation every hour.
- extract a hashmap from attribute names to commands from `nix-locate --at-root --no-group --top-level /bin/ --type x --type s` and merge this information into `NixpkgsEntry.Derivation`
- use this to populate a `package_commands` field in the ElasticSearch backend
- tell the frontend about it

Also we really need to stop exposing the reversed fields to the search, or at least give them a very low weight. I still don't know why we need them.

**Comment by garbas** [comment]
:+1: to use `nix-index`, but does nix-index works with other flakes? can we improve nix-index to also work with other flakes?

> Also we really need to stop exposing the reversed fields to the search, or at least give them a very low weight. I still don't know why we need them.

This was used before the wildcard field was used (2 versions of elasticsearch back).

**Comment by ncfavier** [comment]
No, it won't work with flakes. nix-index queries Hydra for file listings from built derivations, so unless we set up a build farm for the flakes we index, won't happen (and that sounds like a bad idea).

> This was used before the wildcard field was used (2 versions of elasticsearch back).

So I guess we can remove it now? (That doesn't really tell me why it was needed)

**Comment by ncfavier** [comment]
Done in https://github.com/NixOS/nixos-search/pull/610. No need to run nix-index ourselves, we can just use the channel's programs.sqlite file (which happens to be generated using nix-index since [very recently](https://github.com/NixOS/nixos-channel-scripts/pull/62) but this is completely irrelevant).
