### ISSUE TITLE
Question: How long will 22.05 remain searchable?

### ISSUE THREAD

**Issue by MrRacoon** [NixOS/nixos-search#578]
We're running Nixos in production, and the last time the main channel was switched it looked like the previous channels were removed from the search site. This made it a little more tough to support previous versions, before we could upgrade everything. 

I'm generally curious if we could keep previous versions for a while, or if already discussed, how long y'all would keep them around?

**Comment by ncfavier** [comment]
We stop indexing a channel when its status goes from `deprecated` to `unmaintained` in [`nixos-org-configurations/channel.nix`](https://github.com/NixOS/nixos-org-configurations/blob/master/channels.nix), so you would have to ask there. FWIW, 21.11 was dropped in [July 2022](https://github.com/NixOS/nixos-org-configurations/pull/211).

**Comment by ncfavier** [comment]
(It may have been dropped from search.nixos.org earlier since we didn't have https://github.com/NixOS/nixos-search/pull/489 yet, but that should not happen any more.)

**Comment by MrRacoon** [comment]
Without knowing too much about how the search does what it do, is it possible to keep older versions around for longer? 

We've got a handle on our versions now, but I can expect others may find themselves in a situation where they inherit old infra, that may need decent amount of testing before pushing new versions, and could benefit from having those older versions searchable.

**Comment by ncfavier** [comment]
It's possible, but not really a priority AFAIK. You can always use `man configuration.nix` or `nixos-help` on those older machines.

**Comment by MrRacoon** [comment]
Lot more convenient with the search site, especially when flipping between versions to determine how to change things that need to change. 

I would just consider that there is a use case for keeping the older versions. It's a big help to some. If it isn't too much extra work, some of us would really appreciate it.
