### ISSUE TITLE
From/result page is shared between options and packages

### ISSUE THREAD

**Issue by laalsaas** [NixOS/nixos-search#594]
### Steps to reproduce:
1. go to [search.nixos.org](https://search.nixos.org)
2. search for something which will yield >50 results in options and packages, for example "system".
3. go to the second page (note that this will create a `from=50` parameter in the url)
4. click on "options" in the top bar.
### experienced behaviour
The site displays the options, beginning with the  51st. The from parameter is carried over from package search.
### Expected behaviour:
The site should display the options beginning with the first option.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixos-search/pull/595
