### ISSUE TITLE
Home page for xl2tpd 404's

### ISSUE THREAD

**Issue by FrostKiwi** [NixOS/nixos-search#598]
As described above, the homepage link for xl2tpd is broken.
https://search.nixos.org/packages?channel=22.11&show=xl2tpd&from=0&size=50&sort=relevance&type=packages&query=L2TP

**Comment by ysndr** [comment]
The hosmepage address is not set in nixos-search, we only pull the data from the nixpkgs package collection

For this package the file in question is 

https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/tools/networking/xl2tpd/default.nix#L24

Please file an issue upstream

**Comment by FrostKiwi** [comment]
> The hosmepage address is not set in nixos-search, we only pull the data from the nixpkgs package collection
> 
> For this package the file in question is
> 
> https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/tools/networking/xl2tpd/default.nix#L24
> 
> Please file an issue there

Ohh, didn't know that, will do

**Comment by ncfavier** [comment]
Fixed https://github.com/NixOS/nixpkgs/pull/210504
