### ISSUE TITLE
[review] Searching for a partially or fully qualified option name fails

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#62]
*As part of the review for https://github.com/NixOS/nixos-homepage/pull/454*

* * *

Search for `boot.initrd`, no result. Even `boot initrd` fails.

This is a **critical** issue.

**Comment by samueldr** [comment]
I am adding to this issue as I *suspect* it's from the same root cause. Search for `extraFilesConf`, which is part of an option name for `services.printing.extraFilesConf`. No result on my end

**Comment by samueldr** [comment]
I assume this was a mistake in the issue reference.

**Comment by garbas** [comment]
@samueldr yes, this was a mistake. i think should reference the #63.

**Comment by garbas** [comment]
This was now fixed with #107. The full UX will be visible once #71 gets implemented (WIP in #74 )
