### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by 198d** [NixOS/nixos-search#622]
Example searches:

environment.systemPackages
security.pki
boot.loader
nix.extraOptions
programs.ssh

None of those searches return the result you'd expect. Most don't return any results.

**Comment by 198d** [comment]
Ahh, they do return correctly under the unstable channel, just not with the 22.11 channel selected...

**Comment by ncfavier** [comment]
That's weird. flake-info seems to be correctly generating these options on 22.11, and I don't see anything remotely suspicious in [the logs](https://github.com/NixOS/nixos-search/actions/runs/4230482425/jobs/7347867827) for the last import. Let's see if this fixes itself with the next update...

**Comment by 198d** [comment]
Hmm, still not getting expected results for 22.11. Looking at the job output, it seems like it skips when an index for the nixpkgs SHA (guessing) has already been built. Wondering if the job that produced the current incomplete index failed someway through. Maybe need to delete the current index and let the next hourly try and recreate?

**Comment by ncfavier** [comment]
Yes, by the next update I meant the next time the nixos-22.11 channel updates. I could just bump the VERSION file though.

The logs I linked are from the last non-skipped 22.11 update, so if that failed it failed very sneakily...

**Comment by 198d** [comment]
_Something_ happened...the last apparent full import for unstable seems to have taken ~30 minutes vs ~10 minutes for that job...

See you kicked off another job. Thanks for the quick reply and action. 🤞 this fixes things!

**Comment by ncfavier** [comment]
Great, now both channels are affected 🙃

@garbas are we hitting some kind of limit with the elasticsearch instance?

**Comment by ch1bo** [comment]
I'm also affected. A workaround for me right now is to use mynixos.com, e.g.

https://mynixos.com/search?q=environment.systemPackages

**Comment by Skarlett** [comment]
Found another one

Query: `services.gnome`
https://search.nixos.org/options?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=services.gnome
https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=services.gnome

**Comment by ncfavier** [comment]
Fixed now.
