### ISSUE TITLE
Bottles is installed but it's not starting

### ISSUE THREAD

**Issue by lanarasp** [NixOS/nixos-search#629]
When I install bottles from: https://search.nixos.org/packages?
channel=unstable&show=bottles&from=0&size=50&sort=relevance&type=packages&query=bottles

using nix-env -iA nixpkgs.bottles

It installs successfully but after that it does not start. I'm not using nix OS just the nix package manager.
I have also encointered this problem with a few other applications, does anyone now how to fix it?

**Comment by ncfavier** [comment]
That's not an issue with nixos-search. Open an issue at nixpkgs or at bottles. Preferably with an error message.
