### ISSUE TITLE
[review] Search bar uses visually mismatched items

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#66]
*As part of the review for https://github.com/NixOS/nixos-homepage/pull/454*

* * *

The search input row is pretty visually mismatched.

First of all, it uses different sizes for the inputs. Already it hits quite hard. Though I think the real *crime* is the mostly unstyled `<select />`  next to a completely styled text box.

I know, styling inputs is fraught with perils, as if it was an afterthought with web browsers. Though it really clashes.

**Comment by garbas** [comment]
I don't plan to do this fix at this time. but I would welcome for somebody to spend some time styling the search row.

**Comment by davidak** [comment]
I like it a little bigger, so you feel like your input is important, **but it is HUGE :scream:**

what about this?

![Screenshot from 2020-06-11 20-09-34](https://user-images.githubusercontent.com/91113/84424054-ca868a80-ac1f-11ea-8be5-411e4fd0b823.png)


```
.search-page .search-input .input-append input {
    font-size: 20px;
    height: 24px;
    width: 10em;
}

.search-page .search-input .input-append button {
    font-size: 18px;
    height: 34px;
}
```

**Comment by davidak** [comment]
for the `<select />` see https://github.com/NixOS/nixos-search/issues/92

**Comment by garbas** [comment]
This becomes a non issue with #92 being implemented so it makes sense to close this issue.

**Comment by samueldr** [comment]
The search input is *quite big*, but that wasn't really the issue I personally had. It was the way it was unbalanced.

If @davidak has issues still with the size, a new issue for the input can be opened for discussion I guess.

**Comment by davidak** [comment]
seems ok now
