### ISSUE TITLE
Add the current search to title

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixos-search#661]
I tend to bookmark my option searches as todos. I finally opened my bookmark manager and saw this:
![image](https://github.com/NixOS/nixos-search/assets/140964/4efb1c95-0c67-4498-bd95-2cd19d05ed25)

Would it be possible to reflect the current search term to the `<title>`? With proper sanitation of course.

**Comment by ncfavier** [comment]
Done in https://github.com/NixOS/nixos-search/pull/662

Could you test if https://64859f0cc8f2a601c72a1687--nixos-search.netlify.app/ behaves as you expect?

**Comment by pbsds** [comment]
Works great!
