### ISSUE TITLE
command for python packages is wrong

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#665]
Examples:

1. cchardet

https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=cchardet

Shown command:

`nix-shell -p python311Packages.faust-cchardet`

Actual command:

`nix-shell -p python311Packages.cchardet`

2. Nikola

https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=nikola

Shown command:

`nix-shell -p python311Packages.nikola`

Actual command:

`nix-shell -p python311Packages.Nikola`

probably other as well
the other commands for nix-env and configuration.nix will be wrong as well

**Comment by ncfavier** [comment]
No, those are correct for 23.05 and unstable. 22.11 has the names you're looking for.

https://github.com/NixOS/nixpkgs/blob/27343d6e6b710f386aa5df63bdeb16866a782b74/pkgs/top-level/python-aliases.nix#L65
https://github.com/NixOS/nixpkgs/blob/27343d6e6b710f386aa5df63bdeb16866a782b74/pkgs/top-level/python-packages.nix#L6789

**Comment by davidak** [comment]
@ncfavier you are right. This works:

nix-shell -I nixpkgs=channel:nixos-unstable -p python311Packages.nikola
nix-shell -I nixpkgs=channel:nixos-unstable -p python311Packages.faust-cchardet

I used the command wrong for local checked out nixpkgs.
