### ISSUE TITLE
logRefusedPackets incorrect documented

### ISSUE THREAD

**Issue by txtor** [NixOS/nixos-search#674]
on search.nixos.org the property networking.firewall.logRefusedPackets is documented as having the default value "false", but in the source code the default value is "true".

 [networking.firewall.logRefusedPackets](https://search.nixos.org/options?channel=unstable&show=networking.firewall.logRefusedPackets&from=0&size=50&sort=relevance&type=packages&query=log)

**Comment by ncfavier** [comment]
Look closer, the default is `false`. https://github.com/NixOS/nixpkgs/blob/12303c652b881435065a98729eb7278313041e49/nixos/modules/services/networking/firewall.nix#L91-L93
