### ISSUE TITLE
The package libgcc (GNU Compiler Collection, version 12.3.0) does not seem to be working as expected

### ISSUE THREAD

**Issue by dezlymacauley** [NixOS/nixos-search#710]
I installed it by adding it to my configuration.nix file. 

After rebuilding (sudo nixos-rebuild switch), cargo run (A rust command that needs this package did not work)
gcc --version and 'which gcc' returned no results.

I replaced libgcc in my configuration with the package libgccjit
This one works as intended.

**Comment by ncfavier** [comment]
This has nothing to do with nixos-search but you probably want `gcc`, not `libgcc`.
