### ISSUE TITLE
dark mode support for  "https://search.nixos.org/packages"

### ISSUE THREAD

**Issue by sachinchaudhary1808** [NixOS/nixos-search#717]
![image](https://github.com/NixOS/nixos-search/assets/138745629/b84be384-54da-4d4b-ba30-e6f4867b374e)

hey buddys my eyes hurts when i need to search for a pkg pls add dark mode 

please ! ! ! !

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixos-search/issues/554
