### ISSUE TITLE
[review] Link to hydra job missing

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#72]
*As part of the review for https://github.com/NixOS/nixos-homepage/pull/454*

* * *

https://nixos.org/nixos/packages.html?attr=firefox&channel=nixpkgs-unstable&query=firefox

The **Platforms** link link to the job for the given platform for the given attribute. It is currently missing from the new implementation.

**Comment by samueldr** [comment]
Three issues:


 * [ ] All links point to x86_64-linux forcibly.

```
<a href="https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.hello.x86_64-linux">i686-linux</a>
```

 * [ ] Darwin links will not work

All links to darwin will end up "wrong". The old implementation only added Darwin links for `nixpkgs` channel, not nixos. There is no `nixpkgs.hello.x86_64-darwin` in Hydra for the nixos channels.

This is a *hard* issue to solve *right*. It was only working on the previous implementation because of a decision to use <b>nixpkgs</b>-unstable and <b>nixos</b>-yy.mm.

* [ ] Channel change in links is immediate

This could be seen more as a nitpick, but this is more about keeping things *legit* and well-organized all the way.

It seems that the links are not built using the state from the current search, but from an amalgamation of the current state of the form + the state of the search. I would expect that, for all results, things always end up changing to either **pressing the search button** or **all form changes**. This is currently a mish-mash.

 * Be on `unstable` channel.
 * Search for `hello`.
 * Open the `hello` result
 * Observe where links point to.
 * Change the channel to 20.03 **DO NOT** update using *Search*.
 * Observe the links changing.

**Comment by garbas** [comment]
Yeah, just noticed this as well. nixos-unstable does not include any other platform then x86_64-linux. I'll switch to nixpkgs-unstable while still calling it unstable.

**Comment by garbas** [comment]
Since I also imported the evaluation builds data packages and platforms that have build will be linked to the build directly and not to the hydra job.
