### ISSUE TITLE
Explain differences between certain packages

### ISSUE THREAD

**Issue by thibaultmol** [NixOS/nixos-search#725]
Sorry if it's in the wrong repo, but I noticed a problem for people who only use search.nixos.org

For example: yt-dlp has two versions, one that comes with ffmpeg and such and one without those ( `-light` )
But through the web interface it's not possible to actually understand the difference.
Either there needs to be something in the ui to make this diff clear or the package name should indicate the difference?
https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=yt-dlp
![image](https://github.com/NixOS/nixos-search/assets/1010226/02b63b7b-aede-4076-ba6c-4a32b1d494d6)

**Comment by dasJ** [comment]
This is out of scope for the search since there is no way of knowing how packages are different from one another. This should proably be an issue in [nixpkgs](https://github.com/NixOS/nixpkgs/issues) to elaborate the differences between variants of packages in the descriptions.
