### ISSUE TITLE
Source path bad for gnome extensions

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixos-search#728]
Some packages like [gnomeExtensions.desktop-icons-ng-ding](https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=desktop-icon+gnome) have a bad link to source, as it points to the generic `buildGnomeExtension` function definition:

https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/desktops/gnome/extensions/buildGnomeExtension.nix#L54

**Comment by dasJ** [comment]
The source link uses the metadata provided by nixpkgs:
```
$ nix repl
Welcome to Nix 2.18.1. Type :? for help.

nix-repl> :l <nixpkgs>
Added 20006 variables.

nix-repl> gnomeExtensions.desktop-icons-ng-ding.meta.position
"/nix/store/cslab5wq445yijm8vcpvdr8zi92z8ix3-nixpkgs-23.11-small.tar.gz/nixpkgs/pkgs/desktops/gnome/extensions/buildGnomeExtension.nix:54"
```

 It's probably best to create an issue [there](https://github.com/NixOS/nixpkgs/issues) and ask the GNOME maintainers.
