### ISSUE TITLE
[Bug] Sort dropdown generates invalid URLs

### ISSUE THREAD

**Issue by ja1den** [NixOS/nixos-search#732]
### Description

Currently, changing the sort order results in an invalid URL.

This means if the page is reloaded, it is reset to an empty search.
As a result, bookmarking a search impossible.

I think this also means changing the sort order sometimes doesn't work in normal use either (i.e., without reloading).

### Steps to Reproduce

1. Navigate to https://search.nixos.org/options.
2. Enter a search term (e.g., `boot.loader.systemd-boot`).
3. Change the sort order.
4. Notice the `#` before the `?` in the URL.
5. Reload the page. It should now show an empty search.
6. Delete the `#` in the URL.
7. Reload the page again. It should now show the previous search, albeit still sorted by `relevance`.

### Potential Solution

This issue is caused by the `href="#"` attribute on the links (`a`) rendered in the dropdown.

It should be able to be fixed by:

- changing the attribute to be `href="javascript:;"`
- suppressing the default behaviour of the links with `event.preventDefault()`[^1].

[^1]: https://stackoverflow.com/a/48447130

For reference, the offending line is [here](https://github.com/NixOS/nixos-search/blob/main/frontend/src/Search.elm#L1108).

If I have time today, I'll make a PR with the fix.

**Comment by ja1den** [comment]
Doing a little more testing, it seems like there more places where `#` is used and results in an invalid URL.

I'll try to get them all in my PR.

**Comment by ja1den** [comment]
I tried switching `#` to `javascript:;`, but Elm seems not to like it, reporting:
> This is an XSS vector. Please use ports or web components instead.

I then tried to do the equivalent of `event.preventDefault()` in Elm, but I can't get it to work.
It seems like switching `onClick` to `onClickStop` should work, but the behaviour persists either way.

I don't have enough experience with Elm to progress any further.

For whoever looks at this next, I found that the bug manifests differently when running locally.
Instead of having a `#` appear in the URL, the `#` is written to the URL and then immediately overwritten by the new one, resulting in two history entries.
This means the bug only has symptoms in production, which is probably why it was never caught.

**Comment by dasJ** [comment]
Is this still an issue? I cannot reproduce this on Firefox 126

**Comment by ja1den** [comment]
It appears so.

I can reproduce on Firefox 126, following the steps in my original message.

**Comment by eclairevoyant** [comment]
> 4\. Notice the `#` before the `?` in the URL.

I can't reproduce this, in 5 different browsers across mobile and desktop

**Comment by ja1den** [comment]
It turns out that it's caused by the [ClearURLs](https://github.com/ClearURLs/Addon) extension.

I should have tested this earlier, oops.
