### ISSUE TITLE
Wording when a package doesn't specify meta.platforms is misleading.

### ISSUE THREAD

**Issue by iFreilicht** [NixOS/nixos-search#734]
When opening a package that doesn't specify `meta.platforms`, the message is simply "This package is not available on any platform."

![Screenshot 2024-03-06 at 02 46 38](https://github.com/NixOS/nixos-search/assets/9742635/b791f76c-e02d-4ec4-8e95-7dd07163c278)

This is somewhat misleading, for two reasons. 

1. A user can try to build the package on any platform, even without setting `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1`
2. For `x86_64-linux`, the package will even be cached in hydra, so it's pretty much guaranteed to work.

My optimal solution for this would be to communicate both these caveats, maybe by showing `x86_64-linux` as a supported platform, with an additional disclaimer that the user can try installing the package on any other platform as well, but that it's not guaranteed to work.

Alternatively, the wording could be changed to "This package does not list any supported platforms.", or it might just show `x86_64-linux` as supported, nothing else.

**Comment by lolbinarycat** [comment]
relevant context from Lily Foster in the matrix chatroom:
> it looks like the relevant line to change is <https://github.com/NixOS/nixos-search/blob/a740e60705d3cf137abdc25164e5d437d8297421/frontend/src/Page/Packages.elm#L493>
