### ISSUE TITLE
Results are out of date

### ISSUE THREAD

**Issue by adamcstephens** [NixOS/nixos-search#766]
It appears the results for SNO are not being updated.

I'm not sure how out of date it actually is, but for example the `lexical` package should have been at 0.6.0 for days but SNO is showing 0.5.2. At the latest I suspect this would have been in unstable on 4/28.

https://search.nixos.org/packages?channel=unstable&show=lexical&from=0&size=50&sort=relevance&type=packages&query=lexical
https://github.com/NixOS/nixpkgs/pull/306624

**Comment by garbas** [comment]
Hey! Thank you for opening an issue.

The import of data to elasticsearch is broken since 5 days, see here -> https://github.com/NixOS/nixos-search/actions/workflows/import-to-elasticsearch.yml

The last few days were busy, but I'm looking at getting to working again today/tonight.

**Comment by adamcstephens** [comment]
Thanks!
