### ISSUE TITLE
Channel change in links is immediate (while search is on activating the search action)

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#79]
(Observed when verifying #72 and #70)

* * *

This could be seen more as a nitpick, but this is more about keeping things *legit* and well-organized all the way.

It seems that the links are not built using the state from the current search, but from an amalgamation of the current state of the form + the state of the search. I would expect that, for all results, things always end up changing to either **pressing the search button** or **all form changes**. This is currently a mish-mash.

 * Be on `unstable` channel.
 * Search for `hello`.
 * Open the `hello` result
 * Observe where links point to.
 * Change the channel to 20.03 **DO NOT** update using *Search*.
 * Observe the links changing.

For hydra links, this is not an issue, but for GitHub location, it is. The location for a result across channels can and does change!

**Comment by garbas** [comment]
Yeah, noticed this as well yesterday. I'm going to clear the result and resubmit the query as part of #65 shortly.
