### ISSUE TITLE
Incorrect format for Non-NixOS descriptions in 24.05 channel

### ISSUE THREAD

**Issue by AdwaitChavan** [NixOS/nixos-search#797]
Noticed for multiple packages, under 24.05 channel, that the non-NixOS descriptions have a missing newline before `# with flakes`.

Some screenshots:

### nodejs_22
<img width="907" alt="Screenshot 2024-06-11 at 8 36 15 AM" src="https://github.com/NixOS/nixos-search/assets/57969397/a3a1b774-e254-413d-8dee-085c75bf1232">

### python3
<img width="907" alt="Screenshot 2024-06-11 at 8 38 06 AM" src="https://github.com/NixOS/nixos-search/assets/57969397/17d900f1-0077-4b6f-be05-ce3cf1348a8b">

This makes it inconvenient to copy the command under `# without flakes`

**Comment by wegank** [comment]
Fixed by #799.
