### ISSUE TITLE
Typo: `programs.zsh.autosuggestions` -> `programs.zsh.autosuggestion`

### ISSUE THREAD

**Issue by declspecl** [NixOS/nixos-search#847]
Writing
```
programs.zsh.autosuggestions.enable = true;
```
results in the error "The option `programs.zsh.autosuggestions` does not exist" because the correct option is `programs.zsh.autosuggestion` (no s), as can be seen on this wiki page https://nixos.wiki/wiki/Zsh

**Comment by RossComputerGuy** [comment]
1. Not related to search
2. Please use the official wiki https://wiki.nixos.org/wiki/Zsh

**Comment by declspecl** [comment]
![20241109_23h46m54s_grim](https://github.com/user-attachments/assets/75dedaa5-b315-4993-be8d-39f52e5b6b67)

I believe it is related to search, see image
And thanks for the link, I see that lists `zsh.autosuggestions`. Are both sources not up to date?

**Comment by declspecl** [comment]
Wow 🤦 nevermind this is my fault, the home-manager option is `zsh.autosuggestion` oops!
