### ISSUE TITLE
Normal Description is missing

### ISSUE THREAD

**Issue by 06kellyjac** [NixOS/nixos-search#96]
Long description is still there but the normal description is missing.

![2020-06-12T08:24:08+01:00](https://user-images.githubusercontent.com/9866621/84476636-5501d500-ac86-11ea-95c0-ae337c523914.png)

This might already be resolved in the changes you're already making:
https://discourse.nixos.org/t/marketing-team-meeting-minutes-6/7492
https://github.com/NixOS/nixos-homepage/issues/450

**Comment by garbas** [comment]
Normal description is already included in minimal view of a search result. It is a last column of the result view of packages.
